"""The panel's look, the page's own design values (设计_DCC新面板.md §2): theme.qss and tokens.json beside this file are
generated by tools/dcc_theme.py from webui/src/ui/tokens.css, the icons (icons/*.svg) by tools/dcc_icons.mjs from the
page's React icons — nothing here is a value of its own.

Only our own windows are styled: `apply(root)` sets the style sheet on the panel's root (and on each dialog we open,
whose menus and children inherit it). Never QApplication.setStyleSheet, never the DCC's palette or font: the DCC's own
interface stays exactly as it was. A widget's look is chosen by its objectName and dynamic properties (`mark(w, key,
value)` re-polishes it), never by a style sheet of its own.

Fonts: Qt cannot read the page's woff2 (Geist), so the page's fallback list is used (the first family installed);
sizes are px (logical pixels, scaled with the DCC on a high-DPI screen). Icons are drawn from SVG at the screen's pixel
ratio, `currentColor` replaced by a token's colour, and kept by (name, colour, size, ratio).
"""

from __future__ import annotations

import json
import os
import re

from ..qt import QtCore, QtGui, QtSvg, QtWidgets

HERE = os.path.dirname(os.path.abspath(__file__))
ICONS = os.path.join(HERE, "icons")
_data: dict = {}
_pixmaps: dict = {}
_RGBA = re.compile(r"rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)")


def _load() -> dict:
    if not _data:
        with open(os.path.join(HERE, "tokens.json"), encoding="utf-8") as f:
            _data.update(json.load(f))
        with open(os.path.join(HERE, "theme.qss"), encoding="utf-8") as f:
            _data["qss"] = f.read()
    return _data


def token(name: str) -> str:
    return str(_load()["tokens"].get(name, ""))


def type_colour(data_type: str) -> str:
    """A data type's colour (its family's when it has none of its own; the page's unknown grey for neither)."""
    types = _load()["types"]
    t = str(data_type or "").split("|")[0]
    while t and t not in types:
        t = t.rpartition(".")[0]
    return types.get(t) or types.get("", "#6B6B70")


def color(name_or_value: str) -> QtGui.QColor:
    """A token's colour (name) or a colour written out (#rrggbb, rgba(r, g, b, 0–255))."""
    v = token(name_or_value) or name_or_value
    m = _RGBA.match(v)
    if m:
        return QtGui.QColor(int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4)))
    return QtGui.QColor(v)


def px(name: str) -> int:
    v = token(name)
    try:
        return int(round(float(v.removesuffix("px"))))
    except ValueError:
        return 0


def families(name: str = "font") -> list[str]:
    """The page's font list for `name` (--font / --mono) without the faces only the page carries (Geist)."""
    out = []
    for f in token(name).split(","):
        f = f.strip().strip('"').strip("'")
        if f and not f.lower().startswith("geist") and f not in ("system-ui", "sans-serif", "monospace", "ui-monospace"):
            out.append(f)
    return out


def _family(name: str = "font") -> str:
    try:
        have = set(QtGui.QFontDatabase.families())
    except TypeError:  # PySide2: an instance method
        have = set(QtGui.QFontDatabase().families())
    return next((f for f in families(name) if f in have), "")


def apply(root: QtWidgets.QWidget) -> None:
    """Our look on one of our own windows (the panel, a dialog) and everything inside it — nothing else."""
    root.setStyleSheet(_load()["qss"])
    family = _family()
    if family:
        font = QtGui.QFont(root.font())
        font.setFamily(family)
        root.setFont(font)


def mono_font() -> QtGui.QFont:
    font = QtGui.QFont()
    family = _family("mono")
    if family:
        font.setFamily(family)
    font.setPixelSize(px("fs-sm") or 12)
    return font


def mark(widget: QtWidgets.QWidget, key: str, value) -> None:
    """A dynamic property the style sheet reads (#L2SCard[hover="true"] …), the widget re-polished when it changed."""
    if widget.property(key) == value:
        return
    widget.setProperty(key, value)
    style = widget.style()
    style.unpolish(widget)
    style.polish(widget)
    widget.update()


def ratio(widget: QtWidgets.QWidget | None = None) -> float:
    try:
        if widget is not None:
            return float(widget.devicePixelRatioF())
        screen = QtGui.QGuiApplication.primaryScreen()
        return float(screen.devicePixelRatio()) if screen is not None else 1.0
    except Exception:  # noqa: BLE001 - no screen (offscreen): 1
        return 1.0


def has_icon(name: str) -> bool:
    return os.path.isfile(os.path.join(ICONS, f"{name}.svg"))


def pixmap(name: str, colour: str = "text-2", size: int = 16, dpr: float = 1.0, rotate: int = 0) -> QtGui.QPixmap:
    """One icon (icons/<name>.svg) in a token's colour, `size` logical pixels square, drawn for the pixel ratio."""
    key = (name, colour, size, round(dpr, 2), rotate)
    got = _pixmaps.get(key)
    if got is not None:
        return got
    side = max(1, int(round(size * dpr)))
    pm = QtGui.QPixmap(side, side)
    pm.fill(QtCore.Qt.transparent)
    path = os.path.join(ICONS, f"{name}.svg")
    if QtSvg is not None and os.path.isfile(path):
        with open(path, encoding="utf-8") as f:
            svg = f.read()
        c = color(colour)
        svg = svg.replace("currentColor", c.name())
        if c.alpha() < 255:
            svg = svg.replace("<svg ", f'<svg opacity="{c.alphaF():.3f}" ', 1)
        renderer = QtSvg.QSvgRenderer(QtCore.QByteArray(svg.encode("utf-8")))
        painter = QtGui.QPainter(pm)
        painter.setRenderHint(QtGui.QPainter.Antialiasing)
        if rotate:
            painter.translate(side / 2, side / 2)
            painter.rotate(rotate)
            painter.translate(-side / 2, -side / 2)
        renderer.render(painter, QtCore.QRectF(0, 0, side, side))
        painter.end()
    pm.setDevicePixelRatio(dpr)
    _pixmaps[key] = pm
    return pm


def icon(name: str, colour: str = "text-2", size: int = 16, dpr: float | None = None, rotate: int = 0) -> QtGui.QIcon:
    """An icon for a button: its normal colour, and the text colour when hovered or pressed."""
    dpr = ratio() if dpr is None else dpr
    out = QtGui.QIcon()
    out.addPixmap(pixmap(name, colour, size, dpr, rotate), QtGui.QIcon.Normal)
    out.addPixmap(pixmap(name, "text", size, dpr, rotate), QtGui.QIcon.Active)
    out.addPixmap(pixmap(name, "text-3", size, dpr, rotate), QtGui.QIcon.Disabled)
    return out


def category_mark(category: str, colour: str, size: int = 24, dpr: float = 1.0) -> QtGui.QPixmap:
    """A category's mark as the page draws it (ui/CategoryGlyph.tsx): its drawing (or a plain dot when it has none) in
    its colour, on a rounded square of that colour at 16 % (the page's `${color}29`)."""
    key = ("category", category, colour, size, round(dpr, 2))
    got = _pixmaps.get(key)
    if got is not None:
        return got
    side = max(1, int(round(size * dpr)))
    pm = QtGui.QPixmap(side, side)
    pm.fill(QtCore.Qt.transparent)
    painter = QtGui.QPainter(pm)
    painter.setRenderHint(QtGui.QPainter.Antialiasing)
    tint = QtGui.QColor(colour)
    tint.setAlpha(0x29)
    painter.setPen(QtCore.Qt.NoPen)
    painter.setBrush(tint)
    radius = px("r-xs") * dpr
    painter.drawRoundedRect(QtCore.QRectF(0, 0, side, side), radius, radius)
    name = f"category-{category}"
    inner = int(round(side * 0.5))
    if category and has_icon(name):
        glyph = pixmap(name, colour, size // 2, dpr)
        painter.drawPixmap(int((side - glyph.width()) / 2), int((side - glyph.height()) / 2), glyph)
    else:
        painter.setBrush(QtGui.QColor(colour))
        r = inner * 0.33
        painter.drawEllipse(QtCore.QPointF(side / 2, side / 2), r, r)
    painter.end()
    pm.setDevicePixelRatio(dpr)
    _pixmaps[key] = pm
    return pm


def dot(colour: str, size: int = 8, dpr: float = 1.0) -> QtGui.QPixmap:
    """A data type's colour dot (a 「需要：」 chip)."""
    key = ("dot", colour, size, round(dpr, 2))
    got = _pixmaps.get(key)
    if got is not None:
        return got
    side = max(1, int(round(size * dpr)))
    pm = QtGui.QPixmap(side, side)
    pm.fill(QtCore.Qt.transparent)
    painter = QtGui.QPainter(pm)
    painter.setRenderHint(QtGui.QPainter.Antialiasing)
    painter.setPen(QtCore.Qt.NoPen)
    painter.setBrush(QtGui.QColor(colour))
    painter.drawEllipse(QtCore.QRectF(0.5, 0.5, side - 1, side - 1))
    painter.end()
    pm.setDevicePixelRatio(dpr)
    _pixmaps[key] = pm
    return pm
