"""NVIDIA LuxDiT: HDR environment map (light probe) from one frame or a short clip,
generated by a video diffusion transformer (CogVideoX-5B-I2V fine-tuned) that is
conditioned on the plate and on the direction of every lat-long pixel."""

from __future__ import annotations

from lab2shot.sdk import RESEARCH, EnvSpec, Extension, GitSource, LicenseInfo, Weight, hf_file

LUXDIT_URL = "https://github.com/nv-tlabs/LuxDiT.git"
# main: "update polyhaven test hdri list"; inference code unchanged since the release
# commit "update HF url and model names".
LUXDIT_COMMIT = "a191884afbd757bab546bb01f2eaa967fb80b375"

# Hugging Face repo -> (pinned revision, {file: sha256}). Large files: the LFS sha256 from the
# Hub; small files: hashed from the pinned revision. Stored as weights/<repo name>/<file>.
# Only what the single-frame model needs (upstream's video model is not used).
HF_FILES = {
    # Only the video VAE (0.86 GB) and the scheduler config of the base model: LuxDiT ships its
    # own 5B transformer and needs no text encoder (no prompt). The CogVideoX License.
    # (THUDM/CogVideoX-5b-I2V, the name upstream's config uses, redirects here.)
    "zai-org/CogVideoX-5b-I2V": (
        "a6f0f4858a8395e7429d82493864ce92bf73af11",
        {
            "LICENSE": "f1702a540abe80caa3458a4eb539d8a138ffeab99d971d14a99083726814037e",
            "scheduler/scheduler_config.json": "247ecd6635dae7bf889a7ec69ba951c44d746cb4edef13b9c3b1b16bfeeedba5",
            "vae/config.json": "fe8805ed9e30af09fecf04f870a2f11391cea21ddf1446fe22ba220fa4538238",
            "vae/diffusion_pytorch_model.safetensors": "a410e48d988c8224cef392b68db0654485cfd41f345f4a3a81d3e6b765bb995e",
        },
    ),
    # NVIDIA OneWay Noncommercial License (model card: license: other -> LICENSE.md).
    "nvidia/LuxDiT": (
        "6c10bcbbe11439660d4bad514250e6d30a32999d",
        {
            "LICENSE.md": "40d9f9630ba320ea1617287e085ececfda211335cca90aee3caefa889e8b8135",
            "hdr_merge_mlp/config.json": "d4f19bdba0a8c76b2ac32d4dd8dad13671fa056fca3c35e4e46be69665b74c27",
            "hdr_merge_mlp/diffusion_pytorch_model.safetensors": "91cc157594216c13aa734e718c23c0c293c916f82e7f94a33fe11dab048bf213",
            "luxdit_image/config.json": "38f220bb30c19713b6a5539ac17dfdc97730178cf86b448549e1a0536ece8b23",
            # 5B transformer, bf16, 11.1 GB
            "luxdit_image/diffusion_pytorch_model.safetensors": "14373cebcb5b05880eba20b5015cd938adb65d9871131bfedcca237a724cceea",
            # real-scene LoRA, 0.59 GB
            "luxdit_image/lora/model.safetensors": "ec8410c0f6bc11f070c7f516e49ebfdd28d6a3dd3a39959abb5ed25747a2f7bb",
        },
    ),
}
TAGS = {"nvidia/LuxDiT": "luxdit", "zai-org/CogVideoX-5b-I2V": "cogvideox"}
NOTES = {
    "nvidia/LuxDiT": "LuxDiT 单帧模型 + 真实场景 LoRA + HDR 合成 MLP（NVIDIA OneWay Noncommercial，非商用）",
    "zai-org/CogVideoX-5b-I2V": "CogVideoX-5B-I2V 的视频 VAE 和采样器配置（CogVideoX License：学术研究免费，商用须登记）",
}


def _weights() -> tuple[Weight, ...]:
    return tuple(
        hf_file(
            repo, rev, f,
            key=f"{TAGS[repo]}/{f}",
            dest=f"{repo.split('/')[1]}/{f}",
            note=NOTES[repo],
            sha256=sha256,
        )
        for repo, (rev, files) in HF_FILES.items()
        for f, sha256 in files.items()
    )


class LuxDiT(Extension):
    name = "luxdit"
    sdk = 2  # lab2shot.sdk.SDK_API this adapter is written for
    title = "NVIDIA LuxDiT"
    summary = "生成式光照估计模型，从画面预测高质量 HDR 环境图，光照准确又保住画面的语义"
    homepage = "https://research.nvidia.com/labs/toronto-ai/LuxDiT/"
    source = GitSource(url=LUXDIT_URL, commit=LUXDIT_COMMIT)
    license = LicenseInfo(
        tag=RESEARCH,
        name="NVIDIA OneWay Noncommercial License（代码和权重）· CogVideoX License（VAE）",
        url="https://github.com/nv-tlabs/LuxDiT/blob/main/LICENSE.md",
        summary=(
            "非商用，仅限研究或评估。逐项："
            "LuxDiT 代码和 Hugging Face 上 nvidia/LuxDiT 的全部权重（luxdit_image、luxdit_video 两个 5B 模型、"
            "两个真实场景 LoRA、HDR 合成 MLP）均为 NVIDIA OneWay Noncommercial License："
            "只能非商业使用（研究或评估），再分发须附带同一许可证，结果也不能用于商业项目；"
            "代码里从 diffusers 改来的 CogVideoX 模型/管线文件头是 Apache-2.0，但随仓库一起按 NVIDIA 非商用许可发布。"
            "另外要下载 CogVideoX-5B-I2V（智谱 zai-org / 原 THUDM）的视频 VAE 和采样器配置，为 CogVideoX License："
            "学术研究免费，商用须先在 open.bigmodel.cn 登记取得授权，禁止军事和违法用途。"
            "不需要 CogVideoX 的 T5 文本编码器；不依赖 nvdiffrast（仓库注明立方体贴图全在 CPU 上算）"
        ),
    )
    env = EnvSpec(
        # Upstream: conda Python 3.10, "tested with PyTorch 2.4"; diffusers 0.32.0 etc. from its
        # requirements.txt. The code only uses plain torch ops (SDPA attention, no compiled
        # extensions), so it runs on the same torch 2.8 / CUDA 12.8 stack as other adapters here.
        python="3.11",
        torch=("torch==2.8.0", "torchvision==0.23.0"),
        torch_backend="cu128",
    )
    weights = _weights()


EXTENSION = LuxDiT()
