"""Lab2Shot client for DCC plugins (Houdini, Maya, Nuke), scripts and `lab2shot cook`.

Standard library only, Python 3.7+, and nothing else from lab2shot, so it runs inside any DCC's own Python:
copy this one file next to your plugin as lab2shot_client.py.

Files stay on your side: the client uploads the input files you name (local disk or a shared drive; the same bytes are
sent only once) and fetches what the graph's 「输出」 packed in the task where you say: its zip (which it can also
unpack for you), or only the files you need of it, straight into a folder (the server keeps the same files unpacked for
that). Every output has the same layout: one folder, inside it one sub-folder per output-settings node named after it,
and a lab2shot.json saying what is inside (see docs: DCC 插件). The server never reads or writes your paths. Every
run is a job of your account on the server: log in once with the username and password the administrator gave you
(python lab2shot_client.py login, or Lab2Shot(..., username=, password=)); the client keeps a token for that server in
~/.lab2shot/tokens.json (readable by you only) and sends it with every request. Your jobs, uploads and results are yours
only; they are kept with their task for a few days after it ended (outputs(): a plugin reconnecting after Maya was
closed fetches them then). The client also tells the server which application, computer and OS user it comes from
(for the administrator).

    from lab2shot_client import Lab2Shot

    lab = Lab2Shot("http://render-box:8765", app="maya")  # logged in before (login), or username= / password=
    for tool in lab.tools():
        print(tool["id"], tool["name"], [x["name"] for x in tool["exposed"]])

    written = lab.run(
        "sam_3d_body_moving_camera",
        {"input": "Z:/shots/sh030/plate.mov", "unit": "m"},
        on_event=print,
        out_dir="Z:/shots/sh030",  # where the zip goes (named as the server names it: <graph>_u<account>_<task>.zip)
        frames="1001-1020",  # optional: only these frames (default: every frame the input has)
        extract="Z:/shots/sh030/lab2shot",  # optional: unpack it (<its folder>/scene/scene.usd, .../plate/plate.1001.png)
    )

    for o in lab.outputs():  # every output still kept, newest first
        record = lab.output(o)  # its files: lab2shot.json, scene/scene.usd, ...
        lab.fetch_files(o, "Z:/shots/sh030/lab2shot", only=["scene/scene.usd"])  # just the ones needed

Command line (for testing):
    python lab2shot_client.py --server http://render-box:8765 login   # once: asks your username and password
    python lab2shot_client.py --server http://render-box:8765 tools
    python lab2shot_client.py run sam_3d_body_moving_camera -s input=... --out sh030 --extract sh030 --frames 1001-1020
    python lab2shot_client.py queue
    python lab2shot_client.py outputs [--fetch FOLDER]
"""

import getpass
import hashlib
import http.client
import json
import os
import platform
import re
import socket
import ssl
import sys
import time
import urllib.error
import urllib.request
import zipfile

__all__ = ["Cancelled", "Lab2Shot", "Lab2ShotError", "frame_range", "local_files", "parse_value"]

UPLOAD = "upload:"
TRANSFER_TIMEOUT = 3600.0  # seconds for one file up or down (plates are big)
TOOLS_TIMEOUT = 180.0  # seconds for the tool list: a server just started may still be working out the tools' signatures
_TOKEN = re.compile(r"#+|%0?(\d*)d|\$F(\d*)")
# a file's shape: its name with every digit run left out (a minus sign after a dot, an underscore or the start is part
# of the run), the extension kept whole. Frames of one sequence share it. A standard-library copy of
# lab2shot.io.sequence.shape_of (the two must stay equal): which run is the frame number the server decides.
_RUN = re.compile(r"(?<![^._])-\d+(?![\dA-Za-z])|\d+(?![\dA-Za-z])")
_EXT = re.compile(r"\.[A-Za-z0-9]*[A-Za-z][A-Za-z0-9]*$")


def _shape(name):
    ext = _EXT.search(name)
    stem, suffix = (name[:ext.start()], ext.group()) if ext else (name, "")
    pieces = _RUN.split(stem)
    pieces[-1] += suffix
    return "#".join(p.replace("#", "##") for p in pieces)


def _junk(name):
    return name.startswith(".") or name.lower() in ("thumbs.db", "desktop.ini", "icon\r")


class Lab2ShotError(RuntimeError):
    def __init__(self, text, status=None, code=None):
        super(Lab2ShotError, self).__init__(text)
        self.status = status  # the server's answer (0: no answer; None: not about a request)
        self.code = code  # the message's code when the client said it itself (E-CLIENT-...)


# ---- messages: generated by tools/messages_client.py from lab2shot/i18n/<lang>/messages/client.toml and dcc.toml; do not edit
_MESSAGES = {
    "zh": {
        "E-CLIENT-EMPTYFOLDER": "文件夹是空的：{path}，里面没有能上传的文件",
        "E-CLIENT-NOSEQUENCE": "找不到图像序列：{path}，检查文件名里帧号那一段的写法",
        "E-CLIENT-NOFILE": "找不到文件：{path}",
        "E-CLIENT-FRAMESFORM": "帧范围要写成 起始帧-结束帧，如 1001-1020：{frames}",
        "E-CLIENT-FRAMESORDER": "帧范围的起始帧不能大于结束帧：{first}-{last}",
        "E-CLIENT-LOGINFAILED": "登录没有成功：{why}",
        "E-CLIENT-UNREACHABLE": "连不上 Lab2Shot（{server}）：{reason}",
        "E-CLIENT-UNREACHABLEHOST": "连不上 Lab2Shot（{server}）：{reason}。服务要用 lab2shot ui --host 0.0.0.0 启动",
        "E-CLIENT-LOGINFIRST": "{said}：先登录（python lab2shot_client.py --server {server} login，或 Lab2Shot(..., username=, password=)）",
        "I-CLIENT-LOGINNEEDED": "要先登录",
        "E-CLIENT-CHANGEDWHILESENT": "上传 {path} 时内容变了（文件正在被写？）：等它写完再传",
        "E-CLIENT-CANCELLED": "任务被取消了：要结果就重新提交",
        "dcc.catalog.not_graph": "不是 Lab2Shot 的节点图文件：{path}",
        "dcc.catalog.too_big": "文件太大，不像节点图：{path}",
        "dcc.cli.expires": "（{hours:.0f} 小时后删除）",
        "dcc.cli.failed": "失败：{error}",
        "dcc.cli.gpu_off": "不接任务",
        "dcc.cli.gpu_on": "接任务",
        "dcc.cli.logged_in": "已登录：{name}（{username} · {department}），令牌记在 {file}",
        "dcc.cli.logged_out": "已退出",
        "dcc.cli.password": "密码：",
        "dcc.cli.username": "用户名：",
        "dcc.connection.bad_address": "服务器地址写得不对：{address}（例如 https://lab2shot.example.com）",
        "dcc.connection.not_connected": "还没有连接服务器：先点「登录」，填服务器地址和账号",
        "dcc.connection.unreachable": "连不上服务器 {server}：{error}",
        "dcc.contract.not_an_option": "只能选列出的几项之一",
        "dcc.contract.refused": "「{label}」{why}",
        "dcc.job.ask_import": "结果有 {mb:.0f} MB，导入可能要一会儿，现在导入吗？（不导入的话文件留在 {folder}）",
        "dcc.job.cancelled": "已取消",
        "dcc.job.cancelling": "正在取消…",
        "dcc.job.downloading": "下载结果 {index}/{count}（{mb:.0f} MB）",
        "dcc.job.exporting": "导出 {what}",
        "dcc.job.failed": "出错",
        "dcc.job.file_gone": "绑定的文件不在了：{file}",
        "dcc.job.frames.other": "{first} … {last}（{count} 帧）",
        "dcc.job.gave_up_cook": "服务器一直连不上（{error}）：{step}没有完成。服务器好了以后再点一次「计算」",
        "dcc.job.gave_up_fetch": "服务器一直连不上（{error}）：{step}没有完成。服务器好了以后再点一次「取回结果」（任务 {job} 还在服务器上）",
        "dcc.job.imported": "完成：已导入 {version}（{group}）",
        "dcc.job.imported_note": "{done}；{note}",
        "dcc.job.importing": "正在导入 {mb:.0f} MB",
        "dcc.job.no_outputs": "任务算完了，但没有交付任何结果",
        "dcc.job.no_plane": "结果摄影机没挂图像平面：这次没有输入画面，绑定的摄影机也没带画面（输入不全）。要图像平面就绑定一个画面，或绑定一台带图像平面的摄影机",
        "dcc.job.not_imported": "结果已下载到 {folder}，没有导入",
        "dcc.job.plane_failed": "结果摄影机的图像平面没挂上（{error}）",
        "dcc.job.project": "{host} 工程",
        "dcc.job.queued": "排队第 {position} 位",
        "dcc.job.reconnect": "连不上服务器（可能正在重启），{wait} 秒后重连（第 {attempt}/{tries} 次）",
        "dcc.job.running": "计算：{node}",
        "dcc.job.starting": "准备中",
        "dcc.job.step.connect": "连接服务器",
        "dcc.job.step.download": "下载结果",
        "dcc.job.step.poll": "查询进度",
        "dcc.job.step.read_tool": "读取工具",
        "dcc.job.step.submit": "提交任务",
        "dcc.job.step.upload": "上传输入",
        "dcc.job.submitted": "已提交，排队中",
        "dcc.job.undo_import": "Lab2Shot 导入 {name}",
        "dcc.job.unpacking": "检查并解压结果",
        "dcc.job.uploading": "上传 {done}/{total}",
        "dcc.job.version_gone": "{version} 的文件夹不在了：{folder}",
        "dcc.language.host": "跟随 {host}",
        "dcc.login.address_hint": "服务器地址，例如 https://lab2shot.example.com",
        "dcc.login.connect": "连接",
        "dcc.login.connecting": "正在连接…",
        "dcc.login.fill_all": "服务器地址、账号、密码都要填",
        "dcc.login.no_account": "还没有账号？请到网页端注册",
        "dcc.login.password": "密码",
        "dcc.login.server": "服务器",
        "dcc.login.title": "登录 Lab2Shot",
        "dcc.login.username": "账号",
        "dcc.maya.binding_gone": "（找不到了，请重新绑定）{label}",
        "dcc.maya.bound_gone": "绑定的对象找不到了（删掉了，或换了场景）：{label}，请重新绑定",
        "dcc.maya.cannot_export": "Maya 还不能把这种数据导出成文件：{kind}",
        "dcc.maya.cannot_import": "Maya 这一版还不导入 {ext} 文件",
        "dcc.maya.export_failed": "导出失败：{error}",
        "dcc.maya.import": "导入",
        "dcc.maya.import_failed": "整理结果失败：{error}",
        "dcc.maya.no_joints": "{node} 下面没有关节",
        "dcc.maya.no_mayapy": "找不到这台 Maya 的 mayapy：导出不了",
        "dcc.maya.no_skinned_mesh": "{node} 上没有蒙皮的网格：要导出骨架动画请用「骨架」类输入",
        "dcc.maya.node_gone": "这个 Lab2Shot 节点已经不在场景里了",
        "dcc.maya.not_now": "先不导入",
        "dcc.maya.not_scene_data": "导入的应是整理过的结果数据：{path}",
        "dcc.maya.nothing_written": "没有写出文件：{file}",
        "dcc.maya.plane_label": "{node}：{file}",
        "dcc.maya.plugin_failed": "Maya 的 {plugin} 插件加载不了",
        "dcc.maya.select_first": "先在场景里选中{what}",
        "dcc.maya.settings_changed": "导入改了场景设置（单位 / 向上轴 / 帧速率：{before} → {after}）",
        "dcc.maya.want.camera": "一台摄影机",
        "dcc.maya.want.character": "角色（骨架根关节或角色的顶层组，网格要蒙皮在关节上）",
        "dcc.maya.want.image": "带图像平面的摄影机或图像平面本身，或者点「选文件」选画面",
        "dcc.maya.want.model": "一个网格",
        "dcc.maya.want.skeleton": "骨架的根关节",
        "dcc.maya.want.video": "带视频图像平面的摄影机",
        "dcc.maya.worker_died": "后台 Maya 进程没有正常结束（退出码 {code}），详情见 {log}",
        "dcc.maya.worker_timeout.other": "后台 Maya 进程超过 {minutes} 分钟没有完成，已停下",
        "dcc.menu.log_folder": "日志文件夹",
        "dcc.menu.login": "登录…",
        "dcc.menu.new_node": "新建节点",
        "dcc.menu.open_panel": "打开面板",
        "dcc.menu.open_web": "在网页里打开",
        "dcc.menu.queue": "队列",
        "dcc.nuke.binding_gone": "（找不到了，请重新绑定）{label}",
        "dcc.nuke.bound_gone": "绑定的节点找不到了（删掉了，或换了脚本）：{label}，请重新绑定",
        "dcc.nuke.cannot_export": "Nuke 还不能把这种数据导出成文件：{kind}",
        "dcc.nuke.frame_expression": "{node} 的帧号用了表达式，Lab2Shot 跟不了：改用 offset / start at，或者点「选文件」",
        "dcc.nuke.kept_as_file": "{ext} 在 Nuke 里不建节点，文件留在版本文件夹里",
        "dcc.nuke.node_gone": "这个 Lab2Shot 节点已经不在脚本里了",
        "dcc.nuke.picture_label": "{node}：{file}",
        "dcc.nuke.select_first": "先在节点图里选中{what}",
        "dcc.nuke.settings_changed": "导入改了工程设置（{knobs}），这次导入已撤回",
        "dcc.nuke.unknown_class": "这个版本的 Nuke 没有 {node_class} 节点",
        "dcc.nuke.want.camera": "一台摄影机（Camera）",
        "dcc.nuke.want.image": "一个 Read（画面），或者点「选文件」选画面",
        "dcc.nuke.want.points": "点云文件节点（GeoReference）",
        "dcc.nuke.want.scene": "三维文件节点（GeoImport）",
        "dcc.nuke.want.video": "读视频的 Read",
        "dcc.plugin.imported_already": "{version} 已经导入过了",
        "dcc.plugin.missing_inputs": "还缺输入：{inputs}",
        "dcc.plugin.never_submitted": "这个节点还没有提交过任务",
        "dcc.plugin.no_tool": "先选一个工具（工具清单还没取到时先点「刷新工具」）",
        "dcc.plugin.no_version": "这个节点没有版本 {version}",
        "dcc.plugin.not_connected": "还没有连接服务器：点「登录」",
        "dcc.plugin.nothing_new": "网页里没有算出新的结果（没有点「计算」，或还没算完：算完后点「取回结果」）",
        "dcc.plugin.save_first": "请先保存工程",
        "dcc.plugin.wrong_format": "这个输入读 {accept} 文件，{host} 给它的是 {suffix} 文件：请绑到读这种文件的那个输入上",
        "dcc.plugin.wrong_selection": "选中的东西不是这种数据",
        "dcc.queue.asking": "正在查询…",
        "dcc.queue.empty": "队列是空的",
        "dcc.queue.others": "别人的任务",
        "dcc.queue.position": "第 {position} 位",
        "dcc.queue.refresh": "刷新",
        "dcc.queue.state.cancelled": "已取消",
        "dcc.queue.state.done": "完成",
        "dcc.queue.state.failed": "出错",
        "dcc.queue.state.queued": "排队中",
        "dcc.queue.state.running": "计算中",
        "dcc.queue.title": "Lab2Shot 队列",
        "dcc.results.corrupt": "下载的结果不完整（{member} 校验不对）：重新取回",
        "dcc.results.missing_file": "结果里少了文件：{name}",
        "dcc.results.no_room": "磁盘空间不够：结果约 {size:.0f} MB，解压要 {need:.0f} MB，{folder} 所在的盘只剩 {have:.0f} MB",
        "dcc.results.path_too_long.other": "结果的路径太长（超过 {most} 个字符）：{path}。把{project}放到短一点的路径下",
        "dcc.results.project": "工程",
        "dcc.results.version_exists": "版本文件夹已经存在：{folder}",
        "dcc.safety.not_writable": "文件夹不能写：{folder}（{error}）",
        "dcc.settings.language": "语言",
        "dcc.source.local": "本地文件",
        "dcc.source.mine": "我的模板",
        "dcc.source.node": "节点",
        "dcc.source.preset": "预设模板",
        "dcc.ui.banner.login": "登录",
        "dcc.ui.banner.not_connected": "还没有连接服务器：登录后才能取到工具",
        "dcc.ui.banner.not_logged_in": "{server} 未登录",
        "dcc.ui.banner.retry": "重试",
        "dcc.ui.banner.tools_failed": "工具清单没有取到：{error}",
        "dcc.ui.card.needs": "需要：{types}",
        "dcc.ui.card.needs_word": "需要",
        "dcc.ui.card.no_inputs": "不需要输入",
        "dcc.ui.card.optional": "可选：{types}",
        "dcc.ui.card.optional_word": "可选",
        "dcc.ui.error": "出错：{error}（详情见日志 {log}）",
        "dcc.ui.home.loading": "正在取工具清单…",
        "dcc.ui.home.no_tools": "还没有工具清单：先登录",
        "dcc.ui.home.nothing_found": "没有找到「{search}」",
        "dcc.ui.home.search": "搜索工具",
        "dcc.ui.home.suggested": "适合当前选中",
        "dcc.ui.home.tasks": "本场景的任务",
        "dcc.ui.input.bound": "已绑定：{label}",
        "dcc.ui.input.clear": "清除",
        "dcc.ui.input.frames.other": "{first} … {last} · {count} 帧",
        "dcc.ui.input.none": "这个工具不需要输入",
        "dcc.ui.input.nothing_fits": "场景里选中的东西不能用作这个输入",
        "dcc.ui.input.optional": "可选",
        "dcc.ui.input.pick_file": "选文件",
        "dcc.ui.input.pick_file_title": "选文件",
        "dcc.ui.input.pick_sequence": "选序列",
        "dcc.ui.input.pick_sequence_title": "选图像序列的全部帧（可多选），或其中任意一帧，或视频文件",
        "dcc.ui.input.required": "必需：还没有绑定",
        "dcc.ui.input.use_selected": "用选中的",
        "dcc.ui.menu.language": "语言",
        "dcc.ui.menu.local_graph": "添加本地节点图…",
        "dcc.ui.menu.local_graph_filter": "Lab2Shot 节点图 (*.json)",
        "dcc.ui.menu.local_graph_title": "本地节点图",
        "dcc.ui.menu.log_folder": "日志文件夹",
        "dcc.ui.menu.login": "登录…",
        "dcc.ui.menu.new_node": "新建节点",
        "dcc.ui.menu.queue": "队列",
        "dcc.ui.menu.refresh": "刷新工具",
        "dcc.ui.param.advanced.other": "高级（{count}）",
        "dcc.ui.param.bad_value": "「{label}」写得不对：{value}",
        "dcc.ui.param.blank": "留空",
        "dcc.ui.param.from_scene": "来自场景",
        "dcc.ui.param.from_scene_tip": "这个值是从场景读到的（帧范围、帧速率、焦距……），改了就用你的值",
        "dcc.ui.param.in_web": "在网页里编辑",
        "dcc.ui.param.none": "没有可调的设置",
        "dcc.ui.param.refused": "「{label}」{why}",
        "dcc.ui.param.wired": "由 {wired} 的连接线决定",
        "dcc.ui.run.cancel": "取消",
        "dcc.ui.run.compute": "计算",
        "dcc.ui.run.error": "{status}：{error}",
        "dcc.ui.run.missing": "还缺输入：{inputs}",
        "dcc.ui.run.open_log": "打开日志",
        "dcc.ui.state.cancelled": "已取消",
        "dcc.ui.state.done": "有未导入的结果",
        "dcc.ui.state.failed": "出错",
        "dcc.ui.state.imported": "已导入",
        "dcc.ui.state.new": "未计算",
        "dcc.ui.state.queued": "排队中",
        "dcc.ui.state.running": "计算中",
        "dcc.ui.step.compute": "计算",
        "dcc.ui.step.inputs": "输入",
        "dcc.ui.step.settings": "设置",
        "dcc.ui.tab.all": "全部",
        "dcc.ui.tab.recent": "最近用过",
        "dcc.ui.tool.fetch": "取回结果",
        "dcc.ui.tool.gone": "工具「{name}」不在清单里（刷新工具，或它已被删除、停用）",
        "dcc.ui.tool.more": "更多：取回结果、换工具",
        "dcc.ui.tool.none": "这个节点还没有工具：回到全部工具点一个工具卡片",
        "dcc.ui.tool.open_web": "在网页里打开",
        "dcc.ui.top.all_tools": "全部工具",
        "dcc.ui.top.all_tools_tip": "回到全部工具（当前节点不变）",
        "dcc.ui.top.menu": "更多：登录、刷新工具、新建节点、语言…",
        "dcc.ui.top.offline": "未连接",
        "dcc.ui.version.import_ask": "{version} 已下载但没有导入（文件在 {folder}），现在导入吗？",
        "dcc.ui.version.imported": "已导入",
        "dcc.ui.version.not_imported": "未导入",
        "dcc.ui.version.open_folder": "打开文件夹",
        "dcc.ui.version.title": "结果版本",
        "dcc.web.certificate": "服务器的证书没有通过校验",
        "dcc.web.fell_back": "内嵌窗口打不开（{why}），已改用系统浏览器：在网页里算完后回来点「取回结果」",
        "dcc.web.no_engine": "这个软件里没有内嵌浏览器，已用系统浏览器打开：在网页里算完后回来点「取回结果」",
        "dcc.web.not_loaded": "网页打不开",
        "dcc.web.title": "Lab2Shot 网页",
        "lang.en": "English",
        "lang.zh": "中文",
        "list.etc": " 等",
        "list.more": " 等 {count} 个",
        "list.none": "无",
        "list.sep": "、",
        "type.boxes.label": "人物框",
        "type.curves.label": "动画曲线",
        "type.files.label": "要输出的文件",
        "type.image.1.label": "Mask",
        "type.image.2.label": "UV",
        "type.image.3.label": "RGB",
        "type.image.4.label": "RGBA",
        "type.image.label": "图像",
        "type.list_of": "{type}列表",
        "type.or": "或",
        "type.scene.camera.label": "摄影机",
        "type.scene.character.label": "蒙皮角色",
        "type.scene.curves.label": "三维曲线",
        "type.scene.gaussian.label": "3D 高斯",
        "type.scene.label": "场景",
        "type.scene.light.label": "灯光",
        "type.scene.model.label": "几何体",
        "type.scene.points.label": "点云",
        "type.scene.skeleton.label": "骨架动画",
        "type.tracks2d.label": "2D 跟踪点",
        "type.value.bool.label": "开关",
        "type.value.float.label": "浮点",
        "type.value.int.label": "整数",
        "type.value.label": "数值",
        "type.value.lens.label": "镜头内参",
        "type.value.text.label": "字符串",
        "type.value.vector.label": "向量",
        "type.video.label": "视频",
        "ui.conditions.above_max": "不能大于 {max}",
        "ui.conditions.below_min": "不能小于 {min}",
        "ui.conditions.button_no_value": "按钮没有值",
        "ui.conditions.checkbox_target": "目标参数要是布尔，或者是整数且选项恰好是 0 和 1 两项",
        "ui.conditions.decimal_digits": "小数点后面要有数字",
        "ui.conditions.double_equals": "相等要写两个等号 ==",
        "ui.conditions.end": "结尾",
        "ui.conditions.in_list": "in 后面要跟方括号列表，例如 in [1, 2]",
        "ui.conditions.list_unclosed": "列表少了右方括号 ]，或者两项之间少了逗号",
        "ui.conditions.menu_empty": "下拉至少要有一项",
        "ui.conditions.misplaced": "「{token}」放在这里不对",
        "ui.conditions.never_option": "比的值不对：「{name}」只会是 {options} 之一，不会是 {value}",
        "ui.conditions.never_value": "比的值不对：「{name}」不会是 {value}（{why}）",
        "ui.conditions.not_null": "这个参数不能为空",
        "ui.conditions.not_single": "这个参数不是单个值",
        "ui.conditions.number_too_long.other": "数字太长（最多 {most} 个字符）",
        "ui.conditions.one_of": "只能是 {options} 之一",
        "ui.conditions.paren_unclosed": "少了右括号 )",
        "ui.conditions.syntax": "写法不对（第 {at} 个字附近）：{why}",
        "ui.conditions.too_deep.other": "括号或 not 套得太深（最多 {most} 层）",
        "ui.conditions.unclosed_quote": "字符串没有结束的引号",
        "ui.conditions.unfinished": "表达式没写完",
        "ui.conditions.unknown_char": "不认识的字符「{char}」",
        "ui.conditions.unknown_names": "用到了没有公开的参数：{names}",
        "ui.conditions.want_boolean": "要 true 或 false",
        "ui.conditions.want_integer": "要整数",
        "ui.conditions.want_menu_unfit": "这个参数不能用下拉",
        "ui.conditions.want_number": "要数字",
        "ui.conditions.want_string": "要文字",
    },
    "en": {
        "E-CLIENT-EMPTYFOLDER": "The folder is empty: {path} has no file that can be uploaded",
        "E-CLIENT-NOSEQUENCE": "Sequence not found: {path}; check how the frame number is written in the file names",
        "E-CLIENT-NOFILE": "File not found: {path}",
        "E-CLIENT-FRAMESFORM": "Write the frame range as start-end, e.g. 1001-1020: {frames}",
        "E-CLIENT-FRAMESORDER": "The start frame of the frame range cannot be after its end frame: {first}-{last}",
        "E-CLIENT-LOGINFAILED": "Login failed: {why}",
        "E-CLIENT-UNREACHABLE": "Cannot reach Lab2Shot ({server}): {reason}",
        "E-CLIENT-UNREACHABLEHOST": "Cannot reach Lab2Shot ({server}): {reason}. Start the server with lab2shot ui --host 0.0.0.0",
        "E-CLIENT-LOGINFIRST": "{said}: log in first (python lab2shot_client.py --server {server} login, or Lab2Shot(..., username=, password=))",
        "I-CLIENT-LOGINNEEDED": "Login required",
        "E-CLIENT-CHANGEDWHILESENT": "{path} changed while it was uploaded (is it still being written?): upload it again once it is written",
        "E-CLIENT-CANCELLED": "The job was cancelled: submit it again to get its results",
        "dcc.catalog.not_graph": "Not a Lab2Shot node graph file: {path}",
        "dcc.catalog.too_big": "The file is too large to be a node graph: {path}",
        "dcc.cli.expires": "(deleted in {hours:.0f} hours)",
        "dcc.cli.failed": "Failed: {error}",
        "dcc.cli.gpu_off": "takes no jobs",
        "dcc.cli.gpu_on": "takes jobs",
        "dcc.cli.logged_in": "Logged in: {name} ({username} · {department}); token kept in {file}",
        "dcc.cli.logged_out": "Logged out",
        "dcc.cli.password": "Password: ",
        "dcc.cli.username": "Username: ",
        "dcc.connection.bad_address": "The server address is not valid: {address} (e.g. https://lab2shot.example.com)",
        "dcc.connection.not_connected": "Not connected to a server: click Log In and enter the server address and account",
        "dcc.connection.unreachable": "Cannot reach the server {server}: {error}",
        "dcc.contract.not_an_option": "must be one of the listed options",
        "dcc.contract.refused": "\"{label}\" {why}",
        "dcc.job.ask_import": "The results are {mb:.0f} MB and may take a while to import. Import now? (If not, the files stay in {folder})",
        "dcc.job.cancelled": "Cancelled",
        "dcc.job.cancelling": "Cancelling...",
        "dcc.job.downloading": "Downloading results {index}/{count} ({mb:.0f} MB)",
        "dcc.job.exporting": "Exporting {what}",
        "dcc.job.failed": "Failed",
        "dcc.job.file_gone": "The bound file is gone: {file}",
        "dcc.job.frames.one": "{first} … {last} ({count} frame)",
        "dcc.job.frames.other": "{first} … {last} ({count} frames)",
        "dcc.job.gave_up_cook": "The server stayed unreachable ({error}): {step} did not finish. Once the server is back, click Cook again",
        "dcc.job.gave_up_fetch": "The server stayed unreachable ({error}): {step} did not finish. Once the server is back, click Fetch Results again (job {job} is still on the server)",
        "dcc.job.imported": "Done: imported {version} ({group})",
        "dcc.job.imported_note": "{done}; {note}",
        "dcc.job.importing": "Importing {mb:.0f} MB",
        "dcc.job.no_outputs": "The job finished but delivered no results",
        "dcc.job.no_plane": "No image plane on the result camera: this job had no input image and the bound camera carries none (inputs incomplete). For an image plane, bind an image, or a camera with an image plane",
        "dcc.job.not_imported": "Results downloaded to {folder}, not imported",
        "dcc.job.plane_failed": "The image plane of the result camera could not be attached ({error})",
        "dcc.job.project": "{host} project",
        "dcc.job.queued": "Queued at position {position}",
        "dcc.job.reconnect": "Cannot reach the server (it may be restarting); reconnecting in {wait} s (try {attempt}/{tries})",
        "dcc.job.running": "Cooking: {node}",
        "dcc.job.starting": "Preparing",
        "dcc.job.step.connect": "Connecting to the server",
        "dcc.job.step.download": "Downloading results",
        "dcc.job.step.poll": "Asking for progress",
        "dcc.job.step.read_tool": "Reading the tool",
        "dcc.job.step.submit": "Submitting the job",
        "dcc.job.step.upload": "Uploading inputs",
        "dcc.job.submitted": "Submitted, queued",
        "dcc.job.undo_import": "Lab2Shot Import {name}",
        "dcc.job.unpacking": "Checking and unpacking results",
        "dcc.job.uploading": "Uploading {done}/{total}",
        "dcc.job.version_gone": "The folder of {version} is gone: {folder}",
        "dcc.language.host": "Same as {host}",
        "dcc.login.address_hint": "Server address, e.g. https://lab2shot.example.com",
        "dcc.login.connect": "Connect",
        "dcc.login.connecting": "Connecting...",
        "dcc.login.fill_all": "Fill in the server address, username and password",
        "dcc.login.no_account": "No account yet? Sign up on the web page",
        "dcc.login.password": "Password",
        "dcc.login.server": "Server",
        "dcc.login.title": "Log In to Lab2Shot",
        "dcc.login.username": "Username",
        "dcc.maya.binding_gone": "(not found, bind it again) {label}",
        "dcc.maya.bound_gone": "The bound object is gone (deleted, or another scene): {label}; bind it again",
        "dcc.maya.cannot_export": "Maya cannot export this kind of data to a file yet: {kind}",
        "dcc.maya.cannot_import": "This Maya version does not import {ext} files yet",
        "dcc.maya.export_failed": "Export failed: {error}",
        "dcc.maya.import": "Import",
        "dcc.maya.import_failed": "Preparing the results failed: {error}",
        "dcc.maya.no_joints": "No joints under {node}",
        "dcc.maya.no_mayapy": "Cannot find this Maya's mayapy: cannot export",
        "dcc.maya.no_skinned_mesh": "No skinned mesh on {node}: to export skeleton animation, use a Skeleton input",
        "dcc.maya.node_gone": "This Lab2Shot node is no longer in the scene",
        "dcc.maya.not_now": "Not Now",
        "dcc.maya.not_scene_data": "What is imported must be prepared result data: {path}",
        "dcc.maya.nothing_written": "No file was written: {file}",
        "dcc.maya.plane_label": "{node}: {file}",
        "dcc.maya.plugin_failed": "The Maya plug-in {plugin} does not load",
        "dcc.maya.select_first": "Select in the scene first: {what}",
        "dcc.maya.settings_changed": "The import changed the scene settings (units / up axis / frame rate: {before} → {after})",
        "dcc.maya.want.camera": "a camera",
        "dcc.maya.want.character": "a character (the skeleton's root joint or the character's top group, its meshes skinned to the joints)",
        "dcc.maya.want.image": "a camera with an image plane, or the image plane itself, or click Choose File to pick an image",
        "dcc.maya.want.model": "a mesh",
        "dcc.maya.want.skeleton": "the skeleton's root joint",
        "dcc.maya.want.video": "a camera with a video image plane",
        "dcc.maya.worker_died": "The background Maya process did not end normally (exit code {code}); details in {log}",
        "dcc.maya.worker_timeout.one": "The background Maya process did not finish within {minutes} minute and was stopped",
        "dcc.maya.worker_timeout.other": "The background Maya process did not finish within {minutes} minutes and was stopped",
        "dcc.menu.log_folder": "Log Folder",
        "dcc.menu.login": "Log In...",
        "dcc.menu.new_node": "New Node",
        "dcc.menu.open_panel": "Open Panel",
        "dcc.menu.open_web": "Open in Browser",
        "dcc.menu.queue": "Queue",
        "dcc.nuke.binding_gone": "(not found, bind it again) {label}",
        "dcc.nuke.bound_gone": "The bound node is gone (deleted, or another script): {label}; bind it again",
        "dcc.nuke.cannot_export": "Nuke cannot write this kind of data to a file yet: {kind}",
        "dcc.nuke.frame_expression": "{node} uses a frame expression Lab2Shot cannot follow: use offset / start at, or click Choose File",
        "dcc.nuke.kept_as_file": "{ext}: no node is made in Nuke; the file stays in the version folder",
        "dcc.nuke.node_gone": "This Lab2Shot node is no longer in the script",
        "dcc.nuke.picture_label": "{node}: {file}",
        "dcc.nuke.select_first": "Select {what} in the Node Graph first",
        "dcc.nuke.settings_changed": "The import changed the project settings ({knobs}); this import was taken back",
        "dcc.nuke.unknown_class": "This version of Nuke has no {node_class} node",
        "dcc.nuke.want.camera": "a camera (Camera)",
        "dcc.nuke.want.image": "a Read (the plate), or click Choose File to pick it",
        "dcc.nuke.want.points": "a point cloud file node (GeoReference)",
        "dcc.nuke.want.scene": "a 3D file node (GeoImport)",
        "dcc.nuke.want.video": "a Read of a movie",
        "dcc.plugin.imported_already": "{version} is imported already",
        "dcc.plugin.missing_inputs": "Inputs missing: {inputs}",
        "dcc.plugin.never_submitted": "This node has not submitted a job yet",
        "dcc.plugin.no_tool": "Choose a tool first (if the tool list is not there yet, click Refresh Tools)",
        "dcc.plugin.no_version": "This node has no version {version}",
        "dcc.plugin.not_connected": "Not connected to a server: click Log In",
        "dcc.plugin.nothing_new": "No new result was cooked in the browser (Cook was not clicked, or it has not finished: click Fetch Results once it has)",
        "dcc.plugin.save_first": "Save the project first",
        "dcc.plugin.wrong_format": "This input reads only these file types: {accept}. {host} gives it a {suffix} file: bind it to the input that reads that type",
        "dcc.plugin.wrong_selection": "The selection is not this kind of data",
        "dcc.queue.asking": "Asking...",
        "dcc.queue.empty": "The queue is empty",
        "dcc.queue.others": "Another user's job",
        "dcc.queue.position": "Position {position}",
        "dcc.queue.refresh": "Refresh",
        "dcc.queue.state.cancelled": "Cancelled",
        "dcc.queue.state.done": "Done",
        "dcc.queue.state.failed": "Failed",
        "dcc.queue.state.queued": "Queued",
        "dcc.queue.state.running": "Cooking",
        "dcc.queue.title": "Lab2Shot Queue",
        "dcc.results.corrupt": "The downloaded results are incomplete ({member} fails its check): fetch them again",
        "dcc.results.missing_file": "A file is missing from the results: {name}",
        "dcc.results.no_room": "Not enough disk space: the results are about {size:.0f} MB and need {need:.0f} MB to unpack; the drive of {folder} has {have:.0f} MB left",
        "dcc.results.path_too_long.one": "A result path is too long (over {most} character): {path}. Move the {project} to a shorter path",
        "dcc.results.path_too_long.other": "A result path is too long (over {most} characters): {path}. Move the {project} to a shorter path",
        "dcc.results.project": "project",
        "dcc.results.version_exists": "The version folder already exists: {folder}",
        "dcc.safety.not_writable": "Cannot write to the folder: {folder} ({error})",
        "dcc.settings.language": "Language",
        "dcc.source.local": "Local Files",
        "dcc.source.mine": "My Templates",
        "dcc.source.node": "Nodes",
        "dcc.source.preset": "Preset Templates",
        "dcc.ui.banner.login": "Log In",
        "dcc.ui.banner.not_connected": "Not connected to a server: log in to get the tools",
        "dcc.ui.banner.not_logged_in": "Not logged in to {server}",
        "dcc.ui.banner.retry": "Retry",
        "dcc.ui.banner.tools_failed": "The tool list could not be fetched: {error}",
        "dcc.ui.card.needs": "Needs: {types}",
        "dcc.ui.card.needs_word": "Needs",
        "dcc.ui.card.no_inputs": "Needs no input",
        "dcc.ui.card.optional": "Optional: {types}",
        "dcc.ui.card.optional_word": "Optional",
        "dcc.ui.error": "Error: {error} (details in the log {log})",
        "dcc.ui.home.loading": "Fetching the tool list…",
        "dcc.ui.home.no_tools": "No tool list yet: log in first",
        "dcc.ui.home.nothing_found": "Nothing found for \"{search}\"",
        "dcc.ui.home.search": "Search Tools",
        "dcc.ui.home.suggested": "For the Selection",
        "dcc.ui.home.tasks": "Tasks in This Scene",
        "dcc.ui.input.bound": "Bound: {label}",
        "dcc.ui.input.clear": "Clear",
        "dcc.ui.input.frames.one": "{first} … {last} · {count} frame",
        "dcc.ui.input.frames.other": "{first} … {last} · {count} frames",
        "dcc.ui.input.none": "This tool needs no input",
        "dcc.ui.input.nothing_fits": "Nothing selected in the scene can be used for this input",
        "dcc.ui.input.optional": "Optional",
        "dcc.ui.input.pick_file": "Choose File",
        "dcc.ui.input.pick_file_title": "Choose File",
        "dcc.ui.input.pick_sequence": "Choose Sequence",
        "dcc.ui.input.pick_sequence_title": "Choose every frame of the image sequence (multiple selection), any one of its frames, or a video file",
        "dcc.ui.input.required": "Required: not bound yet",
        "dcc.ui.input.use_selected": "Use Selected",
        "dcc.ui.menu.language": "Language",
        "dcc.ui.menu.local_graph": "Add Local Node Graph…",
        "dcc.ui.menu.local_graph_filter": "Lab2Shot node graph (*.json)",
        "dcc.ui.menu.local_graph_title": "Local Node Graph",
        "dcc.ui.menu.log_folder": "Log Folder",
        "dcc.ui.menu.login": "Log In…",
        "dcc.ui.menu.new_node": "New Node",
        "dcc.ui.menu.queue": "Queue",
        "dcc.ui.menu.refresh": "Refresh Tools",
        "dcc.ui.param.advanced.one": "Advanced ({count})",
        "dcc.ui.param.advanced.other": "Advanced ({count})",
        "dcc.ui.param.bad_value": "\"{label}\" is not written right: {value}",
        "dcc.ui.param.blank": "Leave empty",
        "dcc.ui.param.from_scene": "From Scene",
        "dcc.ui.param.from_scene_tip": "This value was read from the scene (frame range, frame rate, focal length…); change it and yours is used",
        "dcc.ui.param.in_web": "Edit in the web page",
        "dcc.ui.param.none": "No settings to adjust",
        "dcc.ui.param.refused": "\"{label}\" {why}",
        "dcc.ui.param.wired": "Set by the wire from {wired}",
        "dcc.ui.run.cancel": "Cancel",
        "dcc.ui.run.compute": "Cook",
        "dcc.ui.run.error": "{status}: {error}",
        "dcc.ui.run.missing": "Inputs still missing: {inputs}",
        "dcc.ui.run.open_log": "Open Log",
        "dcc.ui.state.cancelled": "Cancelled",
        "dcc.ui.state.done": "Results not imported",
        "dcc.ui.state.failed": "Error",
        "dcc.ui.state.imported": "Imported",
        "dcc.ui.state.new": "Not cooked",
        "dcc.ui.state.queued": "Queued",
        "dcc.ui.state.running": "Cooking",
        "dcc.ui.step.compute": "Cook",
        "dcc.ui.step.inputs": "Inputs",
        "dcc.ui.step.settings": "Settings",
        "dcc.ui.tab.all": "All",
        "dcc.ui.tab.recent": "Recent",
        "dcc.ui.tool.fetch": "Fetch Results",
        "dcc.ui.tool.gone": "The tool \"{name}\" is not in the list (refresh the tools, or it was deleted or disabled)",
        "dcc.ui.tool.more": "More: fetch results, change tool",
        "dcc.ui.tool.none": "This node has no tool yet: go back to all tools and click a tool card",
        "dcc.ui.tool.open_web": "Open in Web Page",
        "dcc.ui.top.all_tools": "All Tools",
        "dcc.ui.top.all_tools_tip": "Back to all tools (the current node stays)",
        "dcc.ui.top.menu": "More: log in, refresh tools, new node, language…",
        "dcc.ui.top.offline": "Not Connected",
        "dcc.ui.version.import_ask": "{version} was downloaded but not imported (the files are in {folder}). Import it now?",
        "dcc.ui.version.imported": "Imported",
        "dcc.ui.version.not_imported": "Not imported",
        "dcc.ui.version.open_folder": "Open Folder",
        "dcc.ui.version.title": "Result Versions",
        "dcc.web.certificate": "The server's certificate did not pass verification",
        "dcc.web.fell_back": "The embedded window did not open ({why}); opened in the system browser instead. Once it has cooked there, come back and click Fetch Results",
        "dcc.web.no_engine": "This application has no embedded browser; opened in the system browser. Once it has cooked there, come back and click Fetch Results",
        "dcc.web.not_loaded": "The page did not load",
        "dcc.web.title": "Lab2Shot Web",
        "lang.en": "English",
        "lang.zh": "中文",
        "list.etc": " …",
        "list.more": " and {count} in all",
        "list.none": "none",
        "list.sep": ", ",
        "type.boxes.label": "Person Boxes",
        "type.curves.label": "Animation Curves",
        "type.files.label": "Files to Output",
        "type.image.1.label": "Mask",
        "type.image.2.label": "UV",
        "type.image.3.label": "RGB",
        "type.image.4.label": "RGBA",
        "type.image.label": "Image",
        "type.list_of": "{type} List",
        "type.or": " or ",
        "type.scene.camera.label": "Camera",
        "type.scene.character.label": "Skinned Character",
        "type.scene.curves.label": "3D Curves",
        "type.scene.gaussian.label": "Gaussian Splats",
        "type.scene.label": "Scene",
        "type.scene.light.label": "Light",
        "type.scene.model.label": "Geometry",
        "type.scene.points.label": "Point Cloud",
        "type.scene.skeleton.label": "Skeleton Animation",
        "type.tracks2d.label": "2D Tracks",
        "type.value.bool.label": "Toggle",
        "type.value.float.label": "Float",
        "type.value.int.label": "Integer",
        "type.value.label": "Value",
        "type.value.lens.label": "Lens Intrinsics",
        "type.value.text.label": "String",
        "type.value.vector.label": "Vector",
        "type.video.label": "Video",
        "ui.conditions.above_max": "Cannot be greater than {max}",
        "ui.conditions.below_min": "Cannot be less than {min}",
        "ui.conditions.button_no_value": "A button has no value",
        "ui.conditions.checkbox_target": "The target parameter must be a toggle, or an integer whose options are exactly 0 and 1",
        "ui.conditions.decimal_digits": "A decimal point must be followed by a digit",
        "ui.conditions.double_equals": "Equality is written with two equals signs: ==",
        "ui.conditions.end": "end",
        "ui.conditions.in_list": "in must be followed by a bracketed list, e.g. in [1, 2]",
        "ui.conditions.list_unclosed": "The list is missing its closing bracket ], or a comma between two items",
        "ui.conditions.menu_empty": "A menu needs at least one item",
        "ui.conditions.misplaced": "\"{token}\" does not belong here",
        "ui.conditions.never_option": "Wrong value to compare: \"{name}\" is only ever one of {options}, never {value}",
        "ui.conditions.never_value": "Wrong value to compare: \"{name}\" is never {value} ({why})",
        "ui.conditions.not_null": "This parameter cannot be empty",
        "ui.conditions.not_single": "This parameter is not a single value",
        "ui.conditions.number_too_long.one": "Number too long (at most {most} character)",
        "ui.conditions.number_too_long.other": "Number too long (at most {most} characters)",
        "ui.conditions.one_of": "Must be one of {options}",
        "ui.conditions.paren_unclosed": "Missing closing parenthesis )",
        "ui.conditions.syntax": "Syntax error (near character {at}): {why}",
        "ui.conditions.too_deep.one": "Parentheses or not nested too deeply (at most {most} level)",
        "ui.conditions.too_deep.other": "Parentheses or not nested too deeply (at most {most} levels)",
        "ui.conditions.unclosed_quote": "String has no closing quote",
        "ui.conditions.unfinished": "The expression is incomplete",
        "ui.conditions.unknown_char": "Unknown character \"{char}\"",
        "ui.conditions.unknown_names": "Uses parameters that are not exposed: {names}",
        "ui.conditions.want_boolean": "Must be true or false",
        "ui.conditions.want_integer": "Must be an integer",
        "ui.conditions.want_menu_unfit": "This parameter cannot be a menu",
        "ui.conditions.want_number": "Must be a number",
        "ui.conditions.want_string": "Must be text",
    },
}
# ---- end of the generated messages


LANGS = ("zh", "en")


def _normal(lang):
    head = re.split(r"[-_.@]", str(lang or "").strip().lower(), maxsplit=1)[0]
    return head if head in LANGS else None


def language_of_environment(environ=None):
    """The language of a terminal: LAB2SHOT_LANG, else the first of LC_ALL / LC_MESSAGES / LANG that is set: Chinese
    unless it names another language (C, POSIX, C.UTF-8 or nothing said: Chinese, the product's default)."""
    environ = os.environ if environ is None else environ
    said = _normal(environ.get("LAB2SHOT_LANG", ""))
    if said:
        return said
    for name in ("LC_ALL", "LC_MESSAGES", "LANG"):
        value = environ.get(name, "")
        if value:
            head = re.split(r"[-_.@]", value.strip().lower(), maxsplit=1)[0]
            return "en" if head and head not in ("zh", "c", "posix") else "zh"
    return "zh"


_LANG = [language_of_environment()]  # what this client and the server it asks speak (set_lang; a Lab2Shot's own lang=)


def set_lang(lang):
    """The language of this client's own words and of what the server says to it (sent as X-Lab2Shot-Lang): zh or en.
    A plugin sets its user's choice (or its DCC's language) here once."""
    _LANG[0] = _normal(lang) or _LANG[0]


def get_lang():
    return _LANG[0]


_PLACEHOLDER = re.compile(r"\{(\w+)(?::[^{}]*)?\}")


def _number(value):
    """A parameter as a number, when it is one (an int or float, or one written out: "1", "1,234")."""
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return value
    if isinstance(value, str) and re.match(r"^-?\d[\d,]*(\.\d+)?$", value.strip()):
        return float(value.strip().replace(",", ""))
    return None


def _plural_count(template, params):
    """The number a plural sentence follows (lab2shot/i18n plural_count): `count`, else the first placeholder of its
    .other form given a number."""
    if "count" in params:
        return _number(params["count"])
    for m in _PLACEHOLDER.finditer(template):
        n = _number(params.get(m.group(1)))
        if n is not None:
            return n
    return None


def text(key, in_lang=None, **params):
    """A word or message of the client's own, by key, in `in_lang` (default: get_lang(); named like lab2shot/i18n t()'s
    keyword, which no placeholder is), from the generated block above;
    a sentence that follows a number in the plural form its number takes (<key>.one / <key>.other: English one for
    exactly 1)."""
    one = _normal(in_lang) or _LANG[0]
    table = _MESSAGES[one]
    if key in table:
        template = table[key]
    else:
        template = table[key + ".other"]  # a key in neither form is a programming error (KeyError)
        n = _plural_count(template, params)
        if one == "en" and n == 1 and key + ".one" in table:
            template = table[key + ".one"]
    return template.format(**params) if params else template


def _say(code, in_lang=None, **params):
    """A message of the client's own, in the catalogue's words (the block above)."""
    return text(code, in_lang, **params)


def _refused(code, status=None, in_lang=None, **params):
    return Lab2ShotError(_say(code, in_lang, **params), status, code)


TRANSFER_TRIES = 8  # a file going up or down is resumed from where it got to this often before giving up


class Cancelled(Exception):
    """The caller's cancel_event was set: the request or transfer in progress stopped (never retried)."""


class _From(object):
    """A file from `offset` on, as a request body (seek(0): back to `offset`, for a request sent again); every chunk
    read checks `stop` (the client's cancel_event)."""

    def __init__(self, f, offset, size, stop=None):
        self.f, self.offset, self.size, self.stop = f, offset, size, stop
        f.seek(offset)

    def read(self, n=-1):
        if self.stop is not None and self.stop.is_set():
            raise Cancelled()
        return self.f.read(n)

    def seek(self, pos, whence=0):
        return self.f.seek(self.offset + pos, whence)

    def __len__(self):
        return self.size - self.offset


def _user():
    try:
        return getpass.getuser()
    except Exception:  # no login name (some services)
        return ""


def local_files(path, sequence=True):
    """What to upload for a path on this machine: (the name nodes read, {name in the upload: local file}).

    - a folder: every file in it (nodes read the folder: a sequence inside is found by itself)
    - a sequence pattern (plate.####.exr, plate.%04d.exr, plate.$F4.exr): its frames
    - one frame of a numbered sequence (plate.1001.exr next to plate.1002.exr, 000000_left.png next to
      000001_left.png ...): every file named alike but for its digits; the server finds the frame's sequence among them
    - any other file: that file
    - several files (a list: the frames picked in a file dialog that selects many): exactly those, named as they are
      in their common folder; the server finds the sequence among them, as for the frames a browser sends
    sequence=False (a parameter that takes one file, e.g. a scene): the file as it is, whatever sits next to it
    (anim_v012.usd next to anim_v011.usd is one file, not a sequence).
    """
    if isinstance(path, (list, tuple)):
        picked = sorted(os.path.abspath(os.path.expanduser(p)) for p in path)
        for p in picked:
            if not os.path.isfile(p):
                raise _refused("E-CLIENT-NOFILE", path=p)
        top = os.path.commonpath([os.path.dirname(p) for p in picked])
        files = {os.path.relpath(p, top).replace(os.sep, "/"): p for p in picked}
        return next(iter(files)), files
    path = os.path.abspath(os.path.expanduser(path))
    if os.path.isdir(path):
        files = {}
        for base, _, names in os.walk(path):
            for n in names:
                if _junk(n):
                    continue
                full = os.path.join(base, n)
                files[os.path.relpath(full, path).replace(os.sep, "/")] = full
        if not files:
            raise _refused("E-CLIENT-EMPTYFOLDER", path=path)
        return "", files
    folder, name = os.path.split(path)
    token = _TOKEN.search(name) if sequence else None
    if token:
        head, tail = name[:token.start()], name[token.end():]
        frame = re.compile(re.escape(head) + r"-?\d+" + re.escape(tail) + "$")
        files = {n: os.path.join(folder, n) for n in os.listdir(folder or ".") if frame.match(n) and not _junk(n)}
        if not files:
            raise _refused("E-CLIENT-NOSEQUENCE", path=path)
        return name, files
    if not os.path.isfile(path):
        raise _refused("E-CLIENT-NOFILE", path=path)
    if sequence and _RUN.search(name):
        shape = _shape(name)
        siblings = {n: os.path.join(folder, n) for n in os.listdir(folder or ".")
                    if not _junk(n) and _shape(n) == shape and os.path.isfile(os.path.join(folder, n))}
        return name, siblings  # the server finds the sequence this frame belongs to among them
    return name, {name: path}


def parse_value(text):
    """A value typed on a command line: JSON when it parses (numbers, true/false, null, lists), else the text."""
    try:
        return json.loads(text)
    except ValueError:
        return text


_RANGE = re.compile(r"^\s*(-?\d+)\s*(?:[-–~]\s*(-?\d+))?\s*$")


def frame_range(frames):
    """The frames to cook as the server takes them, [first, last]: from "1001-1020", "1001" or (1001, 1020); None
    stays None (every frame the inputs have)."""
    if frames is None:
        return None
    try:
        if isinstance(frames, str):
            m = _RANGE.match(frames)
            first, last = int(m.group(1)), int(m.group(2) or m.group(1))
        else:
            first, last = (int(f) for f in frames)
    except (AttributeError, TypeError, ValueError):  # no match, not a pair, not numbers
        raise _refused("E-CLIENT-FRAMESFORM", frames=frames)
    if first > last:
        raise _refused("E-CLIENT-FRAMESORDER", first=first, last=last)
    return [first, last]


def _read_text(path):
    try:
        with open(path, "rb") as f:
            return f.read().decode("utf-8")
    except (IOError, OSError):
        return ""


def _write_text(path, text):
    with open(path, "wb") as f:
        f.write(text.encode("utf-8"))


def _sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 22), b""):
            h.update(chunk)
    return h.hexdigest()


def tokens_file():
    """Where this user keeps a token per server: ~/.lab2shot/tokens.json, {"http://render-box:8765": "..."}."""
    return os.path.join(os.path.expanduser("~"), ".lab2shot", "tokens.json")


def _tokens():
    try:
        with open(tokens_file(), encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, dict) else {}
    except (OSError, ValueError):
        return {}


def device_id_file():
    """Where this computer's own device id (sent at every login: server/auth.py, kept in login_log and the session
    it is single sign-on with) is kept — one per computer and user, not per server."""
    return os.path.join(os.path.expanduser("~"), ".lab2shot", "device.json")


def device_id():
    """This computer's device id: made once, kept in device_id_file()."""
    try:
        with open(device_id_file(), encoding="utf-8") as f:
            found = json.load(f).get("id", "")
        if found:
            return found
    except (OSError, ValueError):
        pass
    import uuid

    made = uuid.uuid4().hex
    folder = os.path.dirname(device_id_file())
    if not os.path.isdir(folder):
        os.makedirs(folder)
    fd = os.open(device_id_file(), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        json.dump({"id": made}, f)
    return made


def _keep_token(server, token):
    """Keep (None: forget) this server's token, in a file only this user can read."""
    kept = _tokens()
    if token:
        kept[server] = token
    else:
        kept.pop(server, None)
    folder = os.path.dirname(tokens_file())
    if not os.path.isdir(folder):
        os.makedirs(folder)
    fd = os.open(tokens_file(), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        json.dump(kept, f)


def _trusting(cafile):
    """The system's trusted certificates and, besides them, the one in `cafile` (ssl.create_default_context(cafile=)
    alone would trust that file only)."""
    context = ssl.create_default_context()
    context.load_verify_locations(cafile=cafile)
    return context


class Lab2Shot(object):
    def __init__(self, server="http://localhost:8765", app=None, timeout=30.0, username=None, password=None, token=None,
                 machine=None, cafile=None, cancel_event=None, transfer_tries=None, lang=None):
        """`app`: what is asking (maya, houdini, nuke, cli, ...; default: this Python's program name). Who is asking
        is your account: `token` (default: the one login() kept for this server), or `username` and `password` (logged
        in once, the token kept). `machine`: the server machine's own token (`lab2shot cook` on that machine reads
        it: it acts as the administrator). `cafile`: the certificate that signed an HTTPS server's own — a Lab2Shot
        server makes its own authority (work/tls/ca.pem), which no machine trusts until it is installed, so every
        caller that has that file hands it over here instead of turning verification off. It is trusted on top of the
        system's certificates, never instead of them (a server with a bought certificate is trusted all the same).
        `cancel_event` (a threading.Event): once set, every request and every chunk of a file going up or down stops
        with Cancelled (a DCC plugin's 「取消」). `transfer_tries`: how often a dropped file transfer is resumed
        (default TRANSFER_TRIES; a caller with retries of its own keeps it short). `lang`: what the server says to this
        client in (zh, en; default: set_lang's), sent with every request (X-Lab2Shot-Lang)."""
        self.server = server.rstrip("/")
        self.lang = _normal(lang)
        self.cancel_event = cancel_event
        self.transfer_tries = TRANSFER_TRIES if transfer_tries is None else int(transfer_tries)
        self.timeout = timeout
        self.machine = machine or ""
        self.token = token or ("" if self.machine else _tokens().get(self.server, ""))
        self._credentials = (username, password) if username and password else None
        self._http = urllib.request.build_opener(
            *([urllib.request.HTTPSHandler(context=_trusting(cafile))]
              if cafile and self.server.startswith("https://") else []))
        app = app or os.path.splitext(os.path.basename(sys.executable))[0] or "python"
        self.client = {  # what the server records about where a job comes from (the administrator sees it)
            "app": app, "hostname": socket.gethostname(), "user": _user(), "platform": platform.platform(),
            "python": platform.python_version(), "pid": os.getpid(),
        }
        self._sent = {}  # (local file, size, mtime) -> sha256 uploaded by this client
        if self._credentials and not self.token:
            self.login(*self._credentials)

    # ------------------------------------------------------------------ http

    def login(self, username, password):
        """Log in with your account: the server gives a token, kept for this server in ~/.lab2shot/tokens.json. Ends
        this account's other DCC plugin or command-line logins (single sign-on: a browser is not affected).
        Returns your account ({username, name, department, expires ...})."""
        body = {"username": username, "password": password, "app": self.client["app"], "device_id": device_id(),
                "hostname": self.client["hostname"]}
        req = urllib.request.Request(self.server + "/api/auth/token", method="POST", data=json.dumps(body).encode("utf-8"),
                                     headers={"Content-Type": "application/json", "Origin": self.server,
                                              "X-Lab2Shot-Lang": self.lang or get_lang()})
        try:
            with self._http.open(req, timeout=self.timeout) as resp:
                got = json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            try:
                detail = json.loads(exc.read().decode("utf-8")).get("detail", "")
            except Exception:
                detail = ""
            raise _refused("E-CLIENT-LOGINFAILED", in_lang=self.lang, why=detail or "HTTP %d" % exc.code)
        except urllib.error.URLError as exc:
            raise _refused("E-CLIENT-UNREACHABLE", in_lang=self.lang, server=self.server, reason=exc.reason)
        self.token = got["token"]
        _keep_token(self.server, self.token)
        return got["user"]

    def logout(self):
        """Log out: this token no longer works, and it is forgotten here."""
        if self.token:
            try:
                self._request("POST", "/api/auth/logout", {})
            except Lab2ShotError:
                pass
        self.token = ""
        _keep_token(self.server, None)

    def _open(self, method, path, data=None, headers=None, timeout=None, again=False):
        """One request, as your account. A token that ran out is renewed once when the username and password were
        given (a file being sent is sent again from its start)."""
        if self.cancel_event is not None and self.cancel_event.is_set():
            raise Cancelled()
        sent = dict(headers or {}, Origin=self.server)
        sent["X-Lab2Shot-Lang"] = self.lang or get_lang()
        if self.machine:
            sent["X-Lab2Shot-Machine"] = self.machine
        elif self.token:
            sent["Authorization"] = "Bearer " + self.token
        req = urllib.request.Request(self.server + path, data=data, method=method, headers=sent)
        try:
            return self._http.open(req, timeout=timeout or self.timeout)
        except urllib.error.HTTPError as exc:
            try:
                body = json.loads(exc.read().decode("utf-8"))
            except Exception:
                body = {}
            if exc.code == 401 and not again and self._credentials and (not hasattr(data, "read") or hasattr(data, "seek")):
                self.login(*self._credentials)
                if hasattr(data, "seek"):
                    data.seek(0)
                return self._open(method, path, data, headers, timeout, again=True)
            if method == "HEAD":
                raise
            if exc.code == 401:
                raise _refused("E-CLIENT-LOGINFIRST", 401, self.lang, said=body.get("detail") or _say("I-CLIENT-LOGINNEEDED", self.lang), server=self.server)
            raise Lab2ShotError(body.get("detail") or "HTTP %d" % exc.code, exc.code)
        except urllib.error.URLError as exc:
            raise _refused("E-CLIENT-UNREACHABLEHOST", 0, self.lang, server=self.server, reason=exc.reason)

    def _pause(self, seconds):
        """Wait before trying again; a set cancel_event ends the wait (Cancelled)."""
        if self.cancel_event is None:
            time.sleep(seconds)
        elif self.cancel_event.wait(seconds):
            raise Cancelled()

    def _request(self, method, path, body=None, timeout=None):
        """`timeout`: seconds to wait for this answer, when it may take longer than the session's (a tool list the
        server is still working out just after it started)."""
        data = json.dumps(body).encode("utf-8") if body is not None else None
        with self._open(method, path, data, {"Content-Type": "application/json"}, timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))

    # ------------------------------------------------------------------ files

    def _send(self, local, size):
        """One file up, in a part the server keeps as it arrives: a dropped line goes on from the byte the server got
        to (asked again, waiting longer each time); returns its sha256 as the server has it."""
        part, offset, tries = None, 0, 0
        while True:
            try:
                if part is None:
                    url, method = "/api/uploads/parts?size=%d" % size, "POST"
                else:
                    with self._open("GET", "/api/uploads/parts/" + part) as resp:
                        state = json.loads(resp.read().decode("utf-8"))
                    if state.get("sha"):
                        return state["sha"]
                    offset = state["offset"]
                    url, method = "/api/uploads/parts/%s?offset=%d" % (part, offset), "PATCH"
                with open(local, "rb") as f:
                    body = _From(f, offset, size, self.cancel_event)
                    headers = {"Content-Type": "application/octet-stream", "Content-Length": str(size - offset)}
                    with self._open(method, url, body, headers, TRANSFER_TIMEOUT) as resp:
                        state = json.loads(resp.read().decode("utf-8"))
                part = state["id"]
                if state.get("sha"):
                    return state["sha"]
            except (Lab2ShotError, ConnectionError, socket.timeout, http.client.HTTPException) as exc:
                # the line dropped, the server away a moment (restarting, busy), or the part moved on meanwhile: asked
                # where it got to and gone on from there; anything else (too big, the disk full) is the answer
                status = getattr(exc, "status", 0)
                tries += 1
                if tries > self.transfer_tries or not (status in (0, 408, 409, 429) or (status or 0) >= 500):
                    raise
                self._pause(0 if status == 409 else min(30, 2 ** tries))

    def upload(self, path, on_event=None, sequence=True):
        """Upload a file, a sequence or a folder of this machine (see local_files; sequence=False: one file); returns
        the reference to put into a file parameter. Files you uploaded before (by content) are not sent again, and a
        dropped line goes on where it stopped."""
        name, files = local_files(path, sequence)
        shas = {}
        listed = sorted(files.items())
        for rel, local in listed:
            st = os.stat(local)
            shas[rel] = self._sent.get((local, st.st_size, st.st_mtime)) or _sha256(local)
        have = set(self._request("POST", "/api/uploads/have", {"shas": sorted(set(shas.values()))})["have"])
        for i, (rel, local) in enumerate(listed):
            st = os.stat(local)
            if shas[rel] not in have:
                got = self._send(local, st.st_size)
                if got != shas[rel]:
                    raise _refused("E-CLIENT-CHANGEDWHILESENT", in_lang=self.lang, path=local)
                have.add(got)
            self._sent[(local, st.st_size, st.st_mtime)] = shas[rel]
            if on_event is not None:
                on_event({"type": "upload", "path": path, "done": i + 1, "total": len(files)})
        # where it came from: the file, the folder, or for frames picked together (a list) the first of them
        origin = path[0] if isinstance(path, (list, tuple)) and path else path
        body = {"name": name, "files": shas, "origin": {"path": os.path.abspath(origin), "client": self.client}}
        return self._request("POST", "/api/uploads", body)["ref"]

    def _download(self, url, target):
        """GET `url` into the file `target`, written aside first (target.part) so a broken transfer never leaves half a
        file. A dropped line goes on from the byte already written (Range), while what the server has is still what
        this download began with (If-Range with its ETag, kept in target.part.etag); otherwise it starts again. A part
        left by an earlier run of this client goes on the same way."""
        os.makedirs(os.path.dirname(target) or ".", exist_ok=True)
        part, kept = target + ".part", target + ".part.etag"
        tries = 0
        while True:
            have = os.path.getsize(part) if os.path.exists(part) else 0
            tag = _read_text(kept) if have else ""
            headers = {"Range": "bytes=%d-" % have, "If-Range": tag} if have and tag else {}
            try:
                with self._open("GET", url, headers=headers, timeout=TRANSFER_TIMEOUT) as resp:
                    resumed = resp.status == 206
                    if not resumed:
                        _write_text(kept, resp.headers.get("ETag", ""))
                    with open(part, "ab" if resumed else "wb") as f:
                        for chunk in iter(lambda: resp.read(1 << 22), b""):
                            if self.cancel_event is not None and self.cancel_event.is_set():
                                raise Cancelled()
                            f.write(chunk)
                break
            except (Lab2ShotError, ConnectionError, socket.timeout, http.client.HTTPException) as exc:
                status = getattr(exc, "status", 0)
                tries += 1
                if status == 416:  # what was written is not a start of it any more: again from the first byte
                    os.remove(part)
                elif tries > self.transfer_tries or not (status in (0, 408, 429) or (status or 0) >= 500):
                    raise
                else:
                    self._pause(min(30, 2 ** tries))
        os.replace(part, target)
        if os.path.exists(kept):
            os.remove(kept)
        return target

    def _output_url(self, output):
        return "/api/tasks/%s/outputs/%s" % (urllib.request.quote(output["task"]), urllib.request.quote(output["pkg"]))

    def output(self, output):
        """One output with every file of its unpacked folder (`files`, relative: lab2shot.json first) and what each
        output-settings node wrote (`outputs`: name, main, files); `output` is an "output" event, an entry of a job's
        outputs, or of outputs()."""
        return self._request("GET", self._output_url(output))

    def fetch(self, output, dest, extract=None):
        """Download an output's zip (an "output" event, an entry of a job's outputs, or of outputs()) to the file
        `dest`, going on from where a broken download stopped. `extract`: also unpack it into this folder (its one top
        folder, named like the zip, lands inside). Returns the paths written (the zip, then what was unpacked)."""
        written = [self._download(self._output_url(output) + "/zip", dest)]
        if extract:
            written += unpack(dest, extract)
        return written

    def fetch_files(self, output, folder, only=None):
        """Fetch files of an output one by one from the server's unpacked copy into `folder` (sub-folders kept), for a
        plugin that needs only part of it: `only` names them as output() lists them (None: every one). Returns the
        paths written."""
        base = self._output_url(output)
        names = self.output(output)["files"] if only is None else list(only)
        # what the server names is written under `folder` and nowhere else: the client never lets an answer decide
        # where on this machine a file lands
        return [self._download("%s/file/%s" % (base, urllib.request.quote(rel)), under(folder, rel))
                for rel in names if under(folder, rel)]

    # ------------------------------------------------------------------ api

    def server_state(self):
        """{"boot", "started", "version", "ui", "restart"}: this run's own id (a restart gives the next one another),
        and any restart in progress (open to everyone: no login needed)."""
        return self._request("GET", "/api/server")

    def admin_restart(self, mode):
        """Restart the server (the administrator only — the command line on the server machine uses its own machine
        token, never a password login, so it never kicks the administrator's browser: lab2shot admin restart): "drain" waits
        for jobs running to finish first (new ones still queue), "now" stops them at once. Returns server_state()."""
        return self._request("POST", "/api/admin/restart", {"mode": mode})

    def admin_stop(self, mode):
        """Stop the server (the configuration menu's 停止服务 and the one-click update, cli/service.py stop): "drain"
        waits for the jobs running to finish first, "now" stops them at once; the waiting jobs are kept for the next
        server. Returns server_state()."""
        return self._request("POST", "/api/admin/stop", {"mode": mode})

    def admin_restart_cancel(self):
        """Call off a restart (or a stop) still waiting for the jobs running: the queue goes on. Returns server_state()."""
        return self._request("POST", "/api/admin/restart/cancel", {})

    def admin_queue(self):
        """The whole queue, every job in full (the administrator only): {"gpus", "jobs", ...}."""
        return self._request("GET", "/api/admin/queue")

    def admin_history(self, user_id, limit=1000):
        """One account's task history, newest first (the administrator only): its jobs as the admin 任务记录 lists them."""
        return self._request("GET", "/api/admin/history?user=%d&limit=%d" % (int(user_id), int(limit)))

    def admin_forget_finished(self, user_id):
        """Delete every finished job of one account, each task whole (the administrator only; queued and computing
        ones are left): {"jobs", "skipped", "bytes"}."""
        return self._request("DELETE", "/api/admin/users/%d/jobs" % int(user_id))

    def admin_unlock(self):
        """Clear the counts of wrong passwords (server/auth.py Limiter): the machine token only (lab2shot admin unlock)."""
        return self._request("POST", "/api/admin/security/unlock", {})

    def admin_cards(self):
        """The administrator's cards view (farm.cards): {"cards", "tiers", "nodes", "waiting"}."""
        return self._request("GET", "/api/admin/cards")

    def admin_authorize(self, uuids):
        """Which GPUs take jobs, by UUID (the administrator only; the whole list replaces the one before). Returns the
        queue view. A card taken away finishes the job it runs, then takes no more."""
        return self._request("PUT", "/api/admin/gpus", {"authorized": list(uuids)})

    def admin_switches(self, gpu=None, compute=None):
        """The 显卡任务 / 计算任务 switches (the administrator only; None: leave as it is). Returns the queue view."""
        body = {k: v for k, v in (("gpu", gpu), ("compute", compute)) if v is not None}
        return self._request("PUT", "/api/admin/queue/switches", body)

    def tools(self):
        """Templates usable as tools, each with its exposed parameters (name, label, value, param spec)."""
        return self._request("GET", "/api/tools", timeout=max(self.timeout, TOOLS_TIMEOUT))["tools"]

    def tool(self, tool_id):
        """One template: its graph, exposed parameters and file parameters."""
        return self._request("GET", "/api/tools/" + urllib.request.quote(tool_id))

    def status(self, graph, display=None):
        """Every node of `graph` (a dict, as submit() takes): what is cached, what can cook, why not, its ports and
        cook policy — what the page asks as it edits; a plugin asks before it runs (POST /api/status)."""
        return self._request("POST", "/api/status", {"graph": graph, "display": display})

    def plan(self, graph, target, force=False):
        """What running `graph` for `target` (a node id) would do: the frames the inputs hold, which nodes would cook
        (the rest is cached) (POST /api/plan — for scripts and DCC clients). No time estimate: the server gives none."""
        return self._request("POST", "/api/plan", {"graph": graph, "target": target, "force": force})

    def derive(self, node_type, params):
        """What a node's own parameters bring out of a file: the layers, views or takes a file parameter holds, listed
        before anything is cooked (POST /api/nodes/<type>/derive)."""
        return self._request("POST", "/api/nodes/%s/derive" % urllib.request.quote(node_type), {"params": params})

    def choices(self, node_type, params, inputs=None):
        """The options a parameter's list takes from the packets wired into the node (which joints a skeleton packet
        holds, which one is guessed) — `inputs`: port -> fingerprint, from a status/packet answer
        (POST /api/nodes/<type>/choices)."""
        return self._request("POST", "/api/nodes/%s/choices" % urllib.request.quote(node_type),
                             {"params": params, "inputs": inputs or {}})

    def packet(self, fingerprint):
        """A result packet's type and metadata (what a cooked node gave: its fingerprint is in a status answer);
        fetch() is for what an 「输出」 packed (GET /api/packet/<fp>)."""
        return self._request("GET", "/api/packet/" + urllib.request.quote(fingerprint))

    def submit(self, template, values=None, targets=None, force=False, frames=None, formats=None, key=None):
        """Queue a run as it is (file values must already be upload references and file names; run() prepares them);
        returns the job id (POST /api/jobs). `template`: template id or name, or the graph itself (a dict); `targets`: the
        「输出」 to cook, each collecting and packing what is wired into it (default: every one). `frames`: only these
        frames, "1001-1020" or (1001, 1020), within those the inputs have; default: the graph's range (every frame).
        `formats`: {kind of 3D data: format} the deliveries are wanted in (GET /api/tools lists the formats; the server
        rewrites the job's graph, or refuses when a kind can't be written so). `key`: this submission's own key (8-64
        letters, digits, _ or -): the same key sent again gets the job it made the first time."""
        graph = template if isinstance(template, dict) else None
        body = {"template": None if graph else template, "graph": graph, "values": values or {},
                "deliver": list(targets or []), "frames": frame_range(frames), "force": force, "client": self.client}
        if formats:
            body["formats"] = dict(formats)
        if key:  # this one submission's key: sent again after a dropped line, it finds the job it made (no second job)
            body["submit"] = key
        return self._request("POST", "/api/jobs", body)["job"]

    def embed(self, to="/"):
        """The address that opens this server's page in a DCC's embedded web window already logged in as you, without
        touching your browser's own login (POST /api/auth/embed: needs this client's token). `to`: the page's own
        address, "/" with an optional "#job=<id>&focus=<node>". The address holds a one-time ticket good for 60
        seconds: open it at once, and don't keep or log it."""
        got = self._request("POST", "/api/auth/embed", {"to": to})
        return self.server + got["url"]

    def poll(self, job, since=0):
        """{"state", "done", "error", "outputs", "events": [...], "next"}; pass "next" back as `since`.
        state: queued / running / done / failed / cancelled."""
        return self._request("GET", "/api/jobs/%s/state?since=%d" % (job, since))

    def cancel(self, job):
        """Stop your job: a waiting one leaves the queue, a running one stops."""
        self._request("POST", "/api/jobs/%s/cancel" % job, {})

    def queue(self):
        """{"gpus": [...], "jobs": [...], "history": [...]}: your jobs, and of everyone else's only how many wait or
        run (anonymous). The history is its own answer on the server (the page polls the queue without it)."""
        q = self._request("GET", "/api/queue")
        q["history"] = self._request("GET", "/api/queue/history")["history"]
        return q

    def outputs(self):
        """Every output of your tasks still kept on the server, newest first: each with task, pkg, node, label, title
        (the graph), name (the zip's file name), bytes, count (its files) and expires (seconds since the epoch; None
        while its task runs). fetch() one, or fetch_files() part of it."""
        return self._request("GET", "/api/outputs")

    def wait(self, job, on_event=None, interval=1.0):
        """Block until the job ends; returns what its 「输出」 nodes packed. Raises Lab2ShotError on failure."""
        since = 0
        while True:
            state = self.poll(job, since)
            since = state["next"]
            for event in state["events"]:
                if on_event is not None:
                    on_event(event)
            if state["done"]:
                if state["state"] == "cancelled":
                    raise _refused("E-CLIENT-CANCELLED")
                if state["error"]:
                    raise Lab2ShotError(state["error"])
                return state["outputs"]
            time.sleep(interval)

    def prepare(self, template, values=None, on_event=None):
        """The values to send: input files named in `values` (or left as local paths in a graph you bring) are
        uploaded and replaced by their references."""
        info = self._request("POST", "/api/tools/describe", {"graph": template}) if isinstance(template, dict) else self.tool(template)
        graph = template if isinstance(template, dict) else info["graph"]
        params = {"%s.%s" % (n["id"], k): v for n in graph["nodes"] for k, v in n.get("params", {}).items()}
        values = dict(values or {})
        for f in info["files"]:
            given = [k for k in (f["name"], f["key"]) if k and k in values]
            value = values.pop(given[0]) if given else params.get(f["key"])
            if not value:
                continue
            if not str(value).startswith(UPLOAD):
                values[f["key"]] = self.upload(value, on_event, sequence=f["widget"] != "file")
            else:
                values[f["key"]] = value
        return values

    def run(self, template, values=None, targets=None, force=False, on_event=None, out_dir=None, frames=None, extract=None):
        """Upload the input files, run, wait, and fetch what each 「输出」 packed (see prepare() and fetch()): its zip
        into `out_dir` (default: the current folder), named as the server names it. `extract`: also unpack every zip
        into this folder (each its own top folder). `frames` as for submit(). Returns the paths written on this machine."""
        frames = frame_range(frames)  # a mistake shows before anything is uploaded
        values = self.prepare(template, values, on_event)
        job = self.submit(template, values, targets, force, frames)
        try:
            outputs = self.wait(job, on_event)
        except KeyboardInterrupt:
            self.cancel(job)
            raise
        written = []
        for o in outputs:
            place = under(out_dir or os.getcwd(), os.path.basename(str(o["name"]).replace("\\", "/")))
            if place:
                written += self.fetch(o, place, extract)
        return written


def under(folder, name):
    """Where a name from the server lands on this machine: inside `folder`, never outside it (None: it leads out, or
    it is not a name at all). THE one place this client decides that — the folder download and unpack() both ask it."""
    root = os.path.abspath(folder)
    text = str(name or "").replace("\\", "/")
    if not text or "\x00" in text or text.startswith("/") or re.match(r"^[A-Za-z]:", text):
        return None
    target = os.path.abspath(os.path.join(root, *text.split("/")))
    return target if target.startswith(root + os.sep) else None


def unpack(archive, folder):
    """Unpack an output's zip into `folder` (its top folder and sub-folders kept); returns the files written. Nothing
    may land outside `folder`."""
    written = []
    with zipfile.ZipFile(archive) as zf:
        for member in zf.infolist():
            target = under(folder, member.filename)
            if member.is_dir() or target is None:
                continue
            os.makedirs(os.path.dirname(target), exist_ok=True)
            with zf.open(member) as src, open(target, "wb") as dst:
                for chunk in iter(lambda: src.read(1 << 22), b""):
                    dst.write(chunk)
            written.append(target)
    return written


# ---------------------------------------------------------------------- command line


def _main(argv=None):
    import argparse

    ap = argparse.ArgumentParser(description="Lab2Shot client")
    ap.add_argument("--server", default="http://localhost:8765")
    ap.add_argument("--lang", choices=LANGS, help="language of what is said (default: LAB2SHOT_LANG, else LANG / LC_ALL)")
    sub = ap.add_subparsers(dest="cmd")
    login = sub.add_parser("login", help="log in with your account (asks the username and password); the token is kept")
    login.add_argument("username", nargs="?")
    sub.add_parser("logout", help="log out and forget the token")
    sub.add_parser("tools")
    sub.add_parser("queue")
    kept = sub.add_parser("outputs")
    kept.add_argument("--fetch", help="download their zips into this folder")
    run = sub.add_parser("run")
    run.add_argument("template")
    run.add_argument("-s", "--set", action="append", default=[], help="name=value")
    run.add_argument("--frames", help="first-last, e.g. 1001-1020")
    run.add_argument("--out", help="download the zips into this folder (default: the current one)")
    run.add_argument("--extract", help="also unpack the zips into this folder")
    run.add_argument("--force", action="store_true")
    args = ap.parse_args(argv)
    if args.lang:
        set_lang(args.lang)
    lab = Lab2Shot(args.server, app="script")
    if args.cmd == "login":
        try:
            user = lab.login(args.username or input(text("dcc.cli.username")), getpass.getpass(text("dcc.cli.password")))
        except Lab2ShotError as exc:
            print(text("dcc.cli.failed", error=exc))
            return 1
        print(text("dcc.cli.logged_in", name=user["name"], username=user["username"], department=user["department"],
                   file=tokens_file()))
        return 0
    if args.cmd == "logout":
        lab.logout()
        print(text("dcc.cli.logged_out"))
        return 0

    if args.cmd == "tools":
        for t in lab.tools():
            print("%s  %s" % (t["id"], t["name"]))
            for x in t["exposed"]:
                print("    %s = %r   %s" % (x["name"], x["value"], x["label"]))
        return 0
    if args.cmd == "queue":
        q = lab.queue()
        for g in q.get("gpus", []):  # present only for accounts that may see the graphics cards
            print("GPU %d %s %s" % (g["index"], g["short_name"], text("dcc.cli.gpu_on" if g["authorized"] else "dcc.cli.gpu_off")))
        for j in q["jobs"]:
            where = (text("dcc.queue.position", position=j["position"]) if j["position"] else
                     (text("list.sep").join(j.get("cards") or []) or text("dcc.queue.state.running")))
            print("%-9s %-8s %s" % (j["state"], where, j.get("title") or text("dcc.queue.others")))
        return 0
    if args.cmd == "outputs":
        for o in lab.outputs():
            left = "" if o.get("expires") is None else "  " + text("dcc.cli.expires", hours=(o["expires"] - time.time()) / 3600)
            print("%s  %s · %s  %s%s" % (o["task"], o["title"], o["label"], o["name"], left))
            place = under(args.fetch, os.path.basename(str(o["name"]))) if args.fetch else None
            if place:
                for path in lab.fetch(o, place):
                    print("✓ %s" % path)
        return 0
    if args.cmd == "run":
        values = {}
        for item in args.set:
            key, _, raw = item.partition("=")
            values[key] = parse_value(raw)

        def show(e):
            if e["type"] == "upload":
                print("↑ %s %d/%d" % (e["path"], e["done"], e["total"]))
            elif e["type"] == "queued":
                print("… " + text("dcc.job.queued", position=e["position"]))
            elif e["type"] == "node_start":
                print("… %s" % e["label"])
            elif e["type"] in ("message", "error"):
                print("! [%s] %s" % (e["code"], e["text"]))

        try:
            for path in lab.run(args.template, values, force=args.force, on_event=show, out_dir=args.out, frames=args.frames,
                                extract=args.extract):
                print("✓ %s" % path)
        except Lab2ShotError as exc:
            print(text("dcc.cli.failed", error=exc))
            return 1
        return 0
    ap.print_help()
    return 2


if __name__ == "__main__":
    raise SystemExit(_main())
