"""Lab2Shot client for DCC plugins (Houdini, Maya, Nuke), scripts and `lab2shot cook`.

Standard library only, Python 3.7+, and nothing else from lab2shot, so it runs inside any DCC's own Python:
copy this one file next to your plugin as lab2shot_client.py.

Files stay on your side: the client uploads the input files you name (local disk or a shared drive; the same bytes are
sent only once) and fetches what the graph's 「输出」 packed in the task where you say: its zip (which it can also
unpack for you), or only the files you need of it, straight into a folder (the server keeps the same files unpacked for
that). Every output has the same layout: one folder, inside it one sub-folder per output-settings node named after it,
and a lab2shot.json saying what is inside (see docs: DCC 插件). The server never reads or writes your paths. Every
run is a job of your account on the server: log in once with the username and password the administrator gave you
(python lab2shot_client.py login, or Lab2Shot(..., username=, password=)); the client keeps a token for that server in
~/.lab2shot/tokens.json (readable by you only) and sends it with every request. Your jobs, uploads and results are yours
only; they are kept with their task for a few days after it ended (outputs(): a plugin reconnecting after Maya was
closed fetches them then). The client also tells the server which application, computer and OS user it comes from
(for the administrator).

    from lab2shot_client import Lab2Shot

    lab = Lab2Shot("http://render-box:8765", app="maya")  # logged in before (login), or username= / password=
    for tool in lab.tools():
        print(tool["id"], tool["name"], [x["name"] for x in tool["exposed"]])

    written = lab.run(
        "sam_3d_body_moving_camera",
        {"input": "Z:/shots/sh030/plate.mov", "unit": "m"},
        on_event=print,
        out_dir="Z:/shots/sh030",  # where the zip goes (named as the server names it: <graph>_u<account>_<task>.zip)
        frames="1001-1020",  # optional: only these frames (default: every frame the input has)
        extract="Z:/shots/sh030/lab2shot",  # optional: unpack it (<its folder>/scene/scene.usd, .../plate/plate.1001.png)
    )

    for o in lab.outputs():  # every output still kept, newest first
        record = lab.output(o)  # its files: lab2shot.json, scene/scene.usd, ...
        lab.fetch_files(o, "Z:/shots/sh030/lab2shot", only=["scene/scene.usd"])  # just the ones needed

Command line (for testing):
    python lab2shot_client.py --server http://render-box:8765 login   # once: asks your username and password
    python lab2shot_client.py --server http://render-box:8765 tools
    python lab2shot_client.py run sam_3d_body_moving_camera -s input=... --out sh030 --extract sh030 --frames 1001-1020
    python lab2shot_client.py queue
    python lab2shot_client.py outputs [--fetch FOLDER]
"""

import getpass
import hashlib
import http.client
import json
import os
import platform
import re
import socket
import ssl
import sys
import time
import urllib.error
import urllib.request
import zipfile

__all__ = ["Lab2Shot", "Lab2ShotError", "frame_range", "local_files", "parse_value"]

UPLOAD = "upload:"
TRANSFER_TIMEOUT = 3600.0  # seconds for one file up or down (plates are big)
_TOKEN = re.compile(r"#+|%0?(\d*)d|\$F(\d*)")
# a file's shape: its name with every digit run left out (a minus sign after a dot, an underscore or the start is part
# of the run), the extension kept whole. Frames of one sequence share it. A standard-library copy of
# lab2shot.io.sequence.shape_of (the two must stay equal): which run is the frame number the server decides.
_RUN = re.compile(r"(?<![^._])-\d+(?![\dA-Za-z])|\d+(?![\dA-Za-z])")
_EXT = re.compile(r"\.[A-Za-z0-9]*[A-Za-z][A-Za-z0-9]*$")


def _shape(name):
    ext = _EXT.search(name)
    stem, suffix = (name[:ext.start()], ext.group()) if ext else (name, "")
    pieces = _RUN.split(stem)
    pieces[-1] += suffix
    return "#".join(p.replace("#", "##") for p in pieces)


def _junk(name):
    return name.startswith(".") or name.lower() in ("thumbs.db", "desktop.ini", "icon\r")


class Lab2ShotError(RuntimeError):
    def __init__(self, text, status=None, code=None):
        super(Lab2ShotError, self).__init__(text)
        self.status = status  # the server's answer (0: no answer; None: not about a request)
        self.code = code  # the message's code when the client said it itself (E-CLIENT-...)


# ---- messages: generated by tools/messages_client.py from lab2shot/messages/client.toml; do not edit
_MESSAGES = {
    "E-CLIENT-EMPTYFOLDER": "文件夹是空的：{path}，里面没有能上传的文件",
    "E-CLIENT-NOSEQUENCE": "找不到序列：{path}，检查文件名里帧号那一段的写法",
    "E-CLIENT-NOFILE": "找不到文件：{path}",
    "E-CLIENT-FRAMESFORM": "帧范围要写成 起始帧-结束帧，如 1001-1020：{frames}",
    "E-CLIENT-FRAMESORDER": "帧范围的起始帧不能大于结束帧：{first}-{last}",
    "E-CLIENT-LOGINFAILED": "登录没有成功：{why}",
    "E-CLIENT-UNREACHABLE": "连不上 Lab2Shot（{server}）：{reason}",
    "E-CLIENT-UNREACHABLEHOST": "连不上 Lab2Shot（{server}）：{reason}。服务要用 lab2shot ui --host 0.0.0.0 启动",
    "E-CLIENT-LOGINFIRST": "{said}：先登录（python lab2shot_client.py --server {server} login，或 Lab2Shot(..., username=, password=)）",
    "I-CLIENT-LOGINNEEDED": "要先登录",
    "E-CLIENT-CHANGEDWHILESENT": "上传 {path} 时内容变了（文件正在被写？）：等它写完再传",
    "E-CLIENT-CANCELLED": "任务被取消了：要结果就重新提交",
}
# ---- end of the generated messages


def _say(code, **params):
    """A message of the client's own, in the catalogue's words (the block above)."""
    return _MESSAGES[code].format(**params)


def _refused(code, status=None, **params):
    return Lab2ShotError(_say(code, **params), status, code)


TRANSFER_TRIES = 8  # a file going up or down is resumed from where it got to this often before giving up


class _From(object):
    """A file from `offset` on, as a request body (seek(0): back to `offset`, for a request sent again)."""

    def __init__(self, f, offset, size):
        self.f, self.offset, self.size = f, offset, size
        f.seek(offset)

    def read(self, n=-1):
        return self.f.read(n)

    def seek(self, pos, whence=0):
        return self.f.seek(self.offset + pos, whence)

    def __len__(self):
        return self.size - self.offset


def _user():
    try:
        return getpass.getuser()
    except Exception:  # no login name (some services)
        return ""


def local_files(path, sequence=True):
    """What to upload for a path on this machine: (the name nodes read, {name in the upload: local file}).

    - a folder: every file in it (nodes read the folder: a sequence inside is found by itself)
    - a sequence pattern (plate.####.exr, plate.%04d.exr, plate.$F4.exr): its frames
    - one frame of a numbered sequence (plate.1001.exr next to plate.1002.exr, 000000_left.png next to
      000001_left.png ...): every file named alike but for its digits; the server finds the frame's sequence among them
    - any other file: that file
    sequence=False (a parameter that takes one file, e.g. a scene): the file as it is, whatever sits next to it
    (anim_v012.usd next to anim_v011.usd is one file, not a sequence).
    """
    path = os.path.abspath(os.path.expanduser(path))
    if os.path.isdir(path):
        files = {}
        for base, _, names in os.walk(path):
            for n in names:
                if _junk(n):
                    continue
                full = os.path.join(base, n)
                files[os.path.relpath(full, path).replace(os.sep, "/")] = full
        if not files:
            raise _refused("E-CLIENT-EMPTYFOLDER", path=path)
        return "", files
    folder, name = os.path.split(path)
    token = _TOKEN.search(name) if sequence else None
    if token:
        head, tail = name[:token.start()], name[token.end():]
        frame = re.compile(re.escape(head) + r"-?\d+" + re.escape(tail) + "$")
        files = {n: os.path.join(folder, n) for n in os.listdir(folder or ".") if frame.match(n) and not _junk(n)}
        if not files:
            raise _refused("E-CLIENT-NOSEQUENCE", path=path)
        return name, files
    if not os.path.isfile(path):
        raise _refused("E-CLIENT-NOFILE", path=path)
    if sequence and _RUN.search(name):
        shape = _shape(name)
        siblings = {n: os.path.join(folder, n) for n in os.listdir(folder or ".")
                    if not _junk(n) and _shape(n) == shape and os.path.isfile(os.path.join(folder, n))}
        return name, siblings  # the server finds the sequence this frame belongs to among them
    return name, {name: path}


def parse_value(text):
    """A value typed on a command line: JSON when it parses (numbers, true/false, null, lists), else the text."""
    try:
        return json.loads(text)
    except ValueError:
        return text


_RANGE = re.compile(r"^\s*(-?\d+)\s*(?:[-–~]\s*(-?\d+))?\s*$")


def frame_range(frames):
    """The frames to cook as the server takes them, [first, last]: from "1001-1020", "1001" or (1001, 1020); None
    stays None (every frame the inputs have)."""
    if frames is None:
        return None
    try:
        if isinstance(frames, str):
            m = _RANGE.match(frames)
            first, last = int(m.group(1)), int(m.group(2) or m.group(1))
        else:
            first, last = (int(f) for f in frames)
    except (AttributeError, TypeError, ValueError):  # no match, not a pair, not numbers
        raise _refused("E-CLIENT-FRAMESFORM", frames=frames)
    if first > last:
        raise _refused("E-CLIENT-FRAMESORDER", first=first, last=last)
    return [first, last]


def _read_text(path):
    try:
        with open(path, "rb") as f:
            return f.read().decode("utf-8")
    except (IOError, OSError):
        return ""


def _write_text(path, text):
    with open(path, "wb") as f:
        f.write(text.encode("utf-8"))


def _sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 22), b""):
            h.update(chunk)
    return h.hexdigest()


def tokens_file():
    """Where this user keeps a token per server: ~/.lab2shot/tokens.json, {"http://render-box:8765": "..."}."""
    return os.path.join(os.path.expanduser("~"), ".lab2shot", "tokens.json")


def _tokens():
    try:
        with open(tokens_file(), encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, dict) else {}
    except (OSError, ValueError):
        return {}


def device_id_file():
    """Where this computer's own device id (sent at every login: server/auth.py, kept in login_log and the session
    it is single sign-on with) is kept — one per computer and user, not per server."""
    return os.path.join(os.path.expanduser("~"), ".lab2shot", "device.json")


def device_id():
    """This computer's device id: made once, kept in device_id_file()."""
    try:
        with open(device_id_file(), encoding="utf-8") as f:
            found = json.load(f).get("id", "")
        if found:
            return found
    except (OSError, ValueError):
        pass
    import uuid

    made = uuid.uuid4().hex
    folder = os.path.dirname(device_id_file())
    if not os.path.isdir(folder):
        os.makedirs(folder)
    fd = os.open(device_id_file(), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        json.dump({"id": made}, f)
    return made


def _keep_token(server, token):
    """Keep (None: forget) this server's token, in a file only this user can read."""
    kept = _tokens()
    if token:
        kept[server] = token
    else:
        kept.pop(server, None)
    folder = os.path.dirname(tokens_file())
    if not os.path.isdir(folder):
        os.makedirs(folder)
    fd = os.open(tokens_file(), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        json.dump(kept, f)


class Lab2Shot(object):
    def __init__(self, server="http://localhost:8765", app=None, timeout=30.0, username=None, password=None, token=None,
                 machine=None, cafile=None):
        """`app`: what is asking (maya, houdini, nuke, cli, ...; default: this Python's program name). Who is asking
        is your account: `token` (default: the one login() kept for this server), or `username` and `password` (logged
        in once, the token kept). `machine`: the server machine's own token (`lab2shot cook` on that machine reads
        it: it acts as the administrator). `cafile`: the certificate that signed an HTTPS server's own — a Lab2Shot
        server makes its own authority (work/tls/ca.pem), which no machine trusts until it is installed, so every
        caller that has that file hands it over here instead of turning verification off."""
        self.server = server.rstrip("/")
        self.timeout = timeout
        self.machine = machine or ""
        self.token = token or ("" if self.machine else _tokens().get(self.server, ""))
        self._credentials = (username, password) if username and password else None
        self._http = urllib.request.build_opener(
            *([urllib.request.HTTPSHandler(context=ssl.create_default_context(cafile=cafile))]
              if cafile and self.server.startswith("https://") else []))
        app = app or os.path.splitext(os.path.basename(sys.executable))[0] or "python"
        self.client = {  # what the server records about where a job comes from (the administrator sees it)
            "app": app, "hostname": socket.gethostname(), "user": _user(), "platform": platform.platform(),
            "python": platform.python_version(), "pid": os.getpid(),
        }
        self._sent = {}  # (local file, size, mtime) -> sha256 uploaded by this client
        if self._credentials and not self.token:
            self.login(*self._credentials)

    # ------------------------------------------------------------------ http

    def login(self, username, password):
        """Log in with your account: the server gives a token, kept for this server in ~/.lab2shot/tokens.json. Ends
        this account's other DCC plugin or command-line logins (single sign-on: a browser is not affected).
        Returns your account ({username, name, department, expires ...})."""
        body = {"username": username, "password": password, "app": self.client["app"], "device_id": device_id(),
                "hostname": self.client["hostname"]}
        req = urllib.request.Request(self.server + "/api/auth/token", method="POST", data=json.dumps(body).encode("utf-8"),
                                     headers={"Content-Type": "application/json", "Origin": self.server})
        try:
            with self._http.open(req, timeout=self.timeout) as resp:
                got = json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            try:
                detail = json.loads(exc.read().decode("utf-8")).get("detail", "")
            except Exception:
                detail = ""
            raise _refused("E-CLIENT-LOGINFAILED", why=detail or "HTTP %d" % exc.code)
        except urllib.error.URLError as exc:
            raise _refused("E-CLIENT-UNREACHABLE", server=self.server, reason=exc.reason)
        self.token = got["token"]
        _keep_token(self.server, self.token)
        return got["user"]

    def logout(self):
        """Log out: this token no longer works, and it is forgotten here."""
        if self.token:
            try:
                self._request("POST", "/api/auth/logout", {})
            except Lab2ShotError:
                pass
        self.token = ""
        _keep_token(self.server, None)

    def _open(self, method, path, data=None, headers=None, timeout=None, again=False):
        """One request, as your account. A token that ran out is renewed once when the username and password were
        given (a file being sent is sent again from its start)."""
        sent = dict(headers or {}, Origin=self.server)
        if self.machine:
            sent["X-Lab2Shot-Machine"] = self.machine
        elif self.token:
            sent["Authorization"] = "Bearer " + self.token
        req = urllib.request.Request(self.server + path, data=data, method=method, headers=sent)
        try:
            return self._http.open(req, timeout=timeout or self.timeout)
        except urllib.error.HTTPError as exc:
            try:
                body = json.loads(exc.read().decode("utf-8"))
            except Exception:
                body = {}
            if exc.code == 401 and not again and self._credentials and (not hasattr(data, "read") or hasattr(data, "seek")):
                self.login(*self._credentials)
                if hasattr(data, "seek"):
                    data.seek(0)
                return self._open(method, path, data, headers, timeout, again=True)
            if method == "HEAD":
                raise
            if exc.code == 401:
                raise _refused("E-CLIENT-LOGINFIRST", 401, said=body.get("detail") or _say("I-CLIENT-LOGINNEEDED"), server=self.server)
            raise Lab2ShotError(body.get("detail") or "HTTP %d" % exc.code, exc.code)
        except urllib.error.URLError as exc:
            raise _refused("E-CLIENT-UNREACHABLEHOST", 0, server=self.server, reason=exc.reason)

    def _request(self, method, path, body=None):
        data = json.dumps(body).encode("utf-8") if body is not None else None
        with self._open(method, path, data, {"Content-Type": "application/json"}) as resp:
            return json.loads(resp.read().decode("utf-8"))

    # ------------------------------------------------------------------ files

    def _send(self, local, size):
        """One file up, in a part the server keeps as it arrives: a dropped line goes on from the byte the server got
        to (asked again, waiting longer each time); returns its sha256 as the server has it."""
        part, offset, tries = None, 0, 0
        while True:
            try:
                if part is None:
                    url, method = "/api/uploads/parts?size=%d" % size, "POST"
                else:
                    with self._open("GET", "/api/uploads/parts/" + part) as resp:
                        state = json.loads(resp.read().decode("utf-8"))
                    if state.get("sha"):
                        return state["sha"]
                    offset = state["offset"]
                    url, method = "/api/uploads/parts/%s?offset=%d" % (part, offset), "PATCH"
                with open(local, "rb") as f:
                    body = _From(f, offset, size)
                    headers = {"Content-Type": "application/octet-stream", "Content-Length": str(size - offset)}
                    with self._open(method, url, body, headers, TRANSFER_TIMEOUT) as resp:
                        state = json.loads(resp.read().decode("utf-8"))
                part = state["id"]
                if state.get("sha"):
                    return state["sha"]
            except (Lab2ShotError, ConnectionError, socket.timeout, http.client.HTTPException) as exc:
                # the line dropped, the server away a moment (restarting, busy), or the part moved on meanwhile: asked
                # where it got to and gone on from there; anything else (too big, the disk full) is the answer
                status = getattr(exc, "status", 0)
                tries += 1
                if tries > TRANSFER_TRIES or not (status in (0, 408, 409, 429) or (status or 0) >= 500):
                    raise
                time.sleep(0 if status == 409 else min(30, 2 ** tries))

    def upload(self, path, on_event=None, sequence=True):
        """Upload a file, a sequence or a folder of this machine (see local_files; sequence=False: one file); returns
        the reference to put into a file parameter. Files you uploaded before (by content) are not sent again, and a
        dropped line goes on where it stopped."""
        name, files = local_files(path, sequence)
        shas = {}
        listed = sorted(files.items())
        for rel, local in listed:
            st = os.stat(local)
            shas[rel] = self._sent.get((local, st.st_size, st.st_mtime)) or _sha256(local)
        have = set(self._request("POST", "/api/uploads/have", {"shas": sorted(set(shas.values()))})["have"])
        for i, (rel, local) in enumerate(listed):
            st = os.stat(local)
            if shas[rel] not in have:
                got = self._send(local, st.st_size)
                if got != shas[rel]:
                    raise _refused("E-CLIENT-CHANGEDWHILESENT", path=local)
                have.add(got)
            self._sent[(local, st.st_size, st.st_mtime)] = shas[rel]
            if on_event is not None:
                on_event({"type": "upload", "path": path, "done": i + 1, "total": len(files)})
        body = {"name": name, "files": shas, "origin": {"path": os.path.abspath(path), "client": self.client}}
        return self._request("POST", "/api/uploads", body)["ref"]

    def _download(self, url, target):
        """GET `url` into the file `target`, written aside first (target.part) so a broken transfer never leaves half a
        file. A dropped line goes on from the byte already written (Range), while what the server has is still what
        this download began with (If-Range with its ETag, kept in target.part.etag); otherwise it starts again. A part
        left by an earlier run of this client goes on the same way."""
        os.makedirs(os.path.dirname(target) or ".", exist_ok=True)
        part, kept = target + ".part", target + ".part.etag"
        tries = 0
        while True:
            have = os.path.getsize(part) if os.path.exists(part) else 0
            tag = _read_text(kept) if have else ""
            headers = {"Range": "bytes=%d-" % have, "If-Range": tag} if have and tag else {}
            try:
                with self._open("GET", url, headers=headers, timeout=TRANSFER_TIMEOUT) as resp:
                    resumed = resp.status == 206
                    if not resumed:
                        _write_text(kept, resp.headers.get("ETag", ""))
                    with open(part, "ab" if resumed else "wb") as f:
                        for chunk in iter(lambda: resp.read(1 << 22), b""):
                            f.write(chunk)
                break
            except (Lab2ShotError, ConnectionError, socket.timeout, http.client.HTTPException) as exc:
                status = getattr(exc, "status", 0)
                tries += 1
                if status == 416:  # what was written is not a start of it any more: again from the first byte
                    os.remove(part)
                elif tries > TRANSFER_TRIES or not (status in (0, 408, 429) or (status or 0) >= 500):
                    raise
                else:
                    time.sleep(min(30, 2 ** tries))
        os.replace(part, target)
        if os.path.exists(kept):
            os.remove(kept)
        return target

    def _output_url(self, output):
        return "/api/tasks/%s/outputs/%s" % (urllib.request.quote(output["task"]), urllib.request.quote(output["pkg"]))

    def output(self, output):
        """One output with every file of its unpacked folder (`files`, relative: lab2shot.json first) and what each
        output-settings node wrote (`outputs`: name, main, files); `output` is an "output" event, an entry of a job's
        outputs, or of outputs()."""
        return self._request("GET", self._output_url(output))

    def fetch(self, output, dest, extract=None):
        """Download an output's zip (an "output" event, an entry of a job's outputs, or of outputs()) to the file
        `dest`, going on from where a broken download stopped. `extract`: also unpack it into this folder (its one top
        folder, named like the zip, lands inside). Returns the paths written (the zip, then what was unpacked)."""
        written = [self._download(self._output_url(output) + "/zip", dest)]
        if extract:
            written += unpack(dest, extract)
        return written

    def fetch_files(self, output, folder, only=None):
        """Fetch files of an output one by one from the server's unpacked copy into `folder` (sub-folders kept), for a
        plugin that needs only part of it: `only` names them as output() lists them (None: every one). Returns the
        paths written."""
        base = self._output_url(output)
        names = self.output(output)["files"] if only is None else list(only)
        # what the server names is written under `folder` and nowhere else: the client never lets an answer decide
        # where on this machine a file lands
        return [self._download("%s/file/%s" % (base, urllib.request.quote(rel)), under(folder, rel))
                for rel in names if under(folder, rel)]

    # ------------------------------------------------------------------ api

    def server_state(self):
        """{"boot", "started", "version", "ui", "restart"}: this run's own id (a restart gives the next one another),
        and any restart in progress (open to everyone: no login needed)."""
        return self._request("GET", "/api/server")

    def admin_restart(self, mode):
        """Restart the server (the administrator only — the command line on the server machine uses its own machine
        token, never a password login, so it never kicks the administrator's browser: lab2shot admin restart): "drain" waits
        for jobs running to finish first (new ones still queue), "now" stops them at once. Returns server_state()."""
        return self._request("POST", "/api/admin/restart", {"mode": mode})

    def admin_stop(self, mode):
        """Stop the server (the configuration menu's 停止服务 and the one-click update, cli/service.py stop): "drain"
        waits for the jobs running to finish first, "now" stops them at once; the waiting jobs are kept for the next
        server. Returns server_state()."""
        return self._request("POST", "/api/admin/stop", {"mode": mode})

    def admin_restart_cancel(self):
        """Call off a restart (or a stop) still waiting for the jobs running: the queue goes on. Returns server_state()."""
        return self._request("POST", "/api/admin/restart/cancel", {})

    def admin_queue(self):
        """The whole queue, every job in full (the administrator only): {"gpus", "jobs", ...}."""
        return self._request("GET", "/api/admin/queue")

    def admin_history(self, user_id, limit=1000):
        """One account's task history, newest first (the administrator only): its jobs as the admin 任务记录 lists them."""
        return self._request("GET", "/api/admin/history?user=%d&limit=%d" % (int(user_id), int(limit)))

    def admin_forget_finished(self, user_id):
        """Delete every finished job of one account, each task whole (the administrator only; queued and computing
        ones are left): {"jobs", "skipped", "bytes"}."""
        return self._request("DELETE", "/api/admin/users/%d/jobs" % int(user_id))

    def admin_unlock(self):
        """Clear the counts of wrong passwords (server/auth.py Limiter): the machine token only (lab2shot admin unlock)."""
        return self._request("POST", "/api/admin/security/unlock", {})

    def admin_cards(self):
        """The administrator's cards view (farm.cards): {"cards", "tiers", "nodes", "waiting"}."""
        return self._request("GET", "/api/admin/cards")

    def admin_authorize(self, uuids):
        """Which GPUs take jobs, by UUID (the administrator only; the whole list replaces the one before). Returns the
        queue view. A card taken away finishes the job it runs, then takes no more."""
        return self._request("PUT", "/api/admin/gpus", {"authorized": list(uuids)})

    def admin_switches(self, gpu=None, compute=None):
        """The 显卡任务 / 计算任务 switches (the administrator only; None: leave as it is). Returns the queue view."""
        body = {k: v for k, v in (("gpu", gpu), ("compute", compute)) if v is not None}
        return self._request("PUT", "/api/admin/queue/switches", body)

    def tools(self):
        """Templates usable as tools, each with its exposed parameters (name, label, value, param spec)."""
        return self._request("GET", "/api/tools")["tools"]

    def tool(self, tool_id):
        """One template: its graph, exposed parameters and file parameters."""
        return self._request("GET", "/api/tools/" + urllib.request.quote(tool_id))

    def status(self, graph, display=None):
        """Every node of `graph` (a dict, as submit() takes): what is cached, what can cook, why not, its ports and
        cook policy — what the page asks as it edits; a plugin asks before it runs (POST /api/status)."""
        return self._request("POST", "/api/status", {"graph": graph, "display": display})

    def plan(self, graph, target, force=False):
        """What running `graph` for `target` (a node id) would do: the frames the inputs hold, which nodes would cook
        (the rest is cached), how long that took last time (POST /api/plan — for scripts and DCC clients)."""
        return self._request("POST", "/api/plan", {"graph": graph, "target": target, "force": force})

    def derive(self, node_type, params):
        """What a node's own parameters bring out of a file: the layers, views or takes a file parameter holds, listed
        before anything is cooked (POST /api/nodes/<type>/derive)."""
        return self._request("POST", "/api/nodes/%s/derive" % urllib.request.quote(node_type), {"params": params})

    def choices(self, node_type, params, inputs=None):
        """The options a parameter's list takes from the packets wired into the node (which joints a skeleton packet
        holds, which one is guessed) — `inputs`: port -> fingerprint, from a status/packet answer
        (POST /api/nodes/<type>/choices)."""
        return self._request("POST", "/api/nodes/%s/choices" % urllib.request.quote(node_type),
                             {"params": params, "inputs": inputs or {}})

    def packet(self, fingerprint):
        """A result packet's type and metadata (what a cooked node gave: its fingerprint is in a status answer);
        fetch() is for what an 「输出」 packed (GET /api/packet/<fp>)."""
        return self._request("GET", "/api/packet/" + urllib.request.quote(fingerprint))

    def submit(self, template, values=None, targets=None, force=False, frames=None):
        """Queue a run as it is (file values must already be upload references and file names; run() prepares them);
        returns the job id (POST /api/jobs). `template`: template id or name, or the graph itself (a dict); `targets`: the
        「输出」 to cook, each collecting and packing what is wired into it (default: every one). `frames`: only these
        frames, "1001-1020" or (1001, 1020), within those the inputs have; default: the graph's range (every frame)."""
        graph = template if isinstance(template, dict) else None
        body = {"template": None if graph else template, "graph": graph, "values": values or {},
                "deliver": list(targets or []), "frames": frame_range(frames), "force": force, "client": self.client}
        return self._request("POST", "/api/jobs", body)["job"]

    def poll(self, job, since=0):
        """{"state", "done", "error", "outputs", "events": [...], "next"}; pass "next" back as `since`.
        state: queued / running / done / failed / cancelled."""
        return self._request("GET", "/api/jobs/%s/state?since=%d" % (job, since))

    def cancel(self, job):
        """Stop your job: a waiting one leaves the queue, a running one stops."""
        self._request("POST", "/api/jobs/%s/cancel" % job, {})

    def queue(self):
        """{"gpus": [...], "jobs": [...], "history": [...]}: your jobs, and of everyone else's only how many wait or
        run (anonymous). The history is its own answer on the server (the page polls the queue without it)."""
        q = self._request("GET", "/api/queue")
        q["history"] = self._request("GET", "/api/queue/history")["history"]
        return q

    def outputs(self):
        """Every output of your tasks still kept on the server, newest first: each with task, pkg, node, label, title
        (the graph), name (the zip's file name), bytes, count (its files) and expires (seconds since the epoch; None
        while its task runs). fetch() one, or fetch_files() part of it."""
        return self._request("GET", "/api/outputs")

    def wait(self, job, on_event=None, interval=1.0):
        """Block until the job ends; returns what its 「输出」 nodes packed. Raises Lab2ShotError on failure."""
        since = 0
        while True:
            state = self.poll(job, since)
            since = state["next"]
            for event in state["events"]:
                if on_event is not None:
                    on_event(event)
            if state["done"]:
                if state["state"] == "cancelled":
                    raise _refused("E-CLIENT-CANCELLED")
                if state["error"]:
                    raise Lab2ShotError(state["error"])
                return state["outputs"]
            time.sleep(interval)

    def prepare(self, template, values=None, on_event=None):
        """The values to send: input files named in `values` (or left as local paths in a graph you bring) are
        uploaded and replaced by their references."""
        info = self._request("POST", "/api/tools/describe", {"graph": template}) if isinstance(template, dict) else self.tool(template)
        graph = template if isinstance(template, dict) else info["graph"]
        params = {"%s.%s" % (n["id"], k): v for n in graph["nodes"] for k, v in n.get("params", {}).items()}
        values = dict(values or {})
        for f in info["files"]:
            given = [k for k in (f["name"], f["key"]) if k and k in values]
            value = values.pop(given[0]) if given else params.get(f["key"])
            if not value:
                continue
            if not str(value).startswith(UPLOAD):
                values[f["key"]] = self.upload(value, on_event, sequence=f["widget"] != "file")
            else:
                values[f["key"]] = value
        return values

    def run(self, template, values=None, targets=None, force=False, on_event=None, out_dir=None, frames=None, extract=None):
        """Upload the input files, run, wait, and fetch what each 「输出」 packed (see prepare() and fetch()): its zip
        into `out_dir` (default: the current folder), named as the server names it. `extract`: also unpack every zip
        into this folder (each its own top folder). `frames` as for submit(). Returns the paths written on this machine."""
        frames = frame_range(frames)  # a mistake shows before anything is uploaded
        values = self.prepare(template, values, on_event)
        job = self.submit(template, values, targets, force, frames)
        try:
            outputs = self.wait(job, on_event)
        except KeyboardInterrupt:
            self.cancel(job)
            raise
        written = []
        for o in outputs:
            place = under(out_dir or os.getcwd(), os.path.basename(str(o["name"]).replace("\\", "/")))
            if place:
                written += self.fetch(o, place, extract)
        return written


def under(folder, name):
    """Where a name from the server lands on this machine: inside `folder`, never outside it (None: it leads out, or
    it is not a name at all). THE one place this client decides that — the folder download and unpack() both ask it."""
    root = os.path.abspath(folder)
    text = str(name or "").replace("\\", "/")
    if not text or "\x00" in text or text.startswith("/") or re.match(r"^[A-Za-z]:", text):
        return None
    target = os.path.abspath(os.path.join(root, *text.split("/")))
    return target if target.startswith(root + os.sep) else None


def unpack(archive, folder):
    """Unpack an output's zip into `folder` (its top folder and sub-folders kept); returns the files written. Nothing
    may land outside `folder`."""
    written = []
    with zipfile.ZipFile(archive) as zf:
        for member in zf.infolist():
            target = under(folder, member.filename)
            if member.is_dir() or target is None:
                continue
            os.makedirs(os.path.dirname(target), exist_ok=True)
            with zf.open(member) as src, open(target, "wb") as dst:
                for chunk in iter(lambda: src.read(1 << 22), b""):
                    dst.write(chunk)
            written.append(target)
    return written


# ---------------------------------------------------------------------- command line


def _main(argv=None):
    import argparse

    ap = argparse.ArgumentParser(description="Lab2Shot client")
    ap.add_argument("--server", default="http://localhost:8765")
    sub = ap.add_subparsers(dest="cmd")
    login = sub.add_parser("login", help="log in with your account (asks the username and password); the token is kept")
    login.add_argument("username", nargs="?")
    sub.add_parser("logout", help="log out and forget the token")
    sub.add_parser("tools")
    sub.add_parser("queue")
    kept = sub.add_parser("outputs")
    kept.add_argument("--fetch", help="download their zips into this folder")
    run = sub.add_parser("run")
    run.add_argument("template")
    run.add_argument("-s", "--set", action="append", default=[], help="name=value")
    run.add_argument("--frames", help="first-last, e.g. 1001-1020")
    run.add_argument("--out", help="download the zips into this folder (default: the current one)")
    run.add_argument("--extract", help="also unpack the zips into this folder")
    run.add_argument("--force", action="store_true")
    args = ap.parse_args(argv)
    lab = Lab2Shot(args.server, app="script")
    if args.cmd == "login":
        try:
            user = lab.login(args.username or input("用户名："), getpass.getpass("密码："))
        except Lab2ShotError as exc:
            print("失败：%s" % exc)
            return 1
        print("已登录：%s（%s · %s），令牌记在 %s" % (user["name"], user["username"], user["department"], tokens_file()))
        return 0
    if args.cmd == "logout":
        lab.logout()
        print("已退出")
        return 0

    if args.cmd == "tools":
        for t in lab.tools():
            print("%s  %s" % (t["id"], t["name"]))
            for x in t["exposed"]:
                print("    %s = %r   %s" % (x["name"], x["value"], x["label"]))
        return 0
    if args.cmd == "queue":
        q = lab.queue()
        for g in q.get("gpus", []):  # present only for accounts that may see the graphics cards
            print("GPU %d %s %s" % (g["index"], g["short_name"], "接任务" if g["authorized"] else "不接任务"))
        for j in q["jobs"]:
            where = "第 %d 位" % j["position"] if j["position"] else ("、".join(j.get("cards") or []) or "计算中")
            print("%-9s %-8s %s" % (j["state"], where, j.get("title") or "别人的任务"))
        return 0
    if args.cmd == "outputs":
        for o in lab.outputs():
            left = "" if o.get("expires") is None else "  (%.0f 小时后删除)" % ((o["expires"] - time.time()) / 3600)
            print("%s  %s · %s  %s%s" % (o["task"], o["title"], o["label"], o["name"], left))
            place = under(args.fetch, os.path.basename(str(o["name"]))) if args.fetch else None
            if place:
                for path in lab.fetch(o, place):
                    print("✓ %s" % path)
        return 0
    if args.cmd == "run":
        values = {}
        for item in args.set:
            key, _, text = item.partition("=")
            values[key] = parse_value(text)

        def show(e):
            if e["type"] == "upload":
                print("↑ %s %d/%d" % (e["path"], e["done"], e["total"]))
            elif e["type"] == "queued":
                print("… 排队第 %d 位" % e["position"])
            elif e["type"] == "node_start":
                print("… %s" % e["label"])
            elif e["type"] in ("message", "error"):
                print("! [%s] %s" % (e["code"], e["text"]))

        try:
            for path in lab.run(args.template, values, force=args.force, on_event=show, out_dir=args.out, frames=args.frames,
                                extract=args.extract):
                print("✓ %s" % path)
        except Lab2ShotError as exc:
            print("失败：%s" % exc)
            return 1
        return 0
    ap.print_help()
    return 2


if __name__ == "__main__":
    raise SystemExit(_main())
