import { GATE_CATALOGUE, LEVELS } from "./generatedGateCatalogue.ts";
import { getLang, getPhrasing, LANGS, type Lang } from "../i18n/lang.ts";
import { listSep, phrased, templateFor } from "../i18n/words.ts";

/** Messages the page says itself, by code: the same rules as the server's lab2shot/messages (LEVEL-MODULE-MEANING,
 * templates with named parameters, formats d , g .Nf .N% only, a list joined with the language's separator). The
 * templates are lab2shot/i18n/<lang>/messages/web.toml's (generated by tools/messages_web.py), one table per
 * language; a message is said in the page's language (i18n/lang.ts). A message that follows a number is written in plural
 * forms ("CODE.one" / "CODE.other", lab2shot/i18n PLURAL_FORMS) and reads in the one its number takes.
 *
 * Before login only the few the gate needs are present (`generatedGateCatalogue.ts`): the full catalogue is over
 * 20 kB and the gate uses only a handful of it. The rest is in `generatedCatalogue.ts`, registered once when site.tsx
 * loads after login (`addCatalogue`); the full catalogue must never be bundled into the login bundle. */

/** The templates registered so far, per language: initially only the gate's, extended by `addCatalogue`. */
const CATALOGUE: Record<Lang, Record<string, string>> = Object.fromEntries(LANGS.map((l) => [l, { ...GATE_CATALOGUE[l] }])) as Record<Lang, Record<string, string>>;

/** Registers more templates (the post-login set). Codes are unique across the catalogue, so registration order does not
 * matter. */
export function addCatalogue(more: Readonly<Record<Lang, Readonly<Record<string, string>>>>): void {
  for (const l of LANGS) Object.assign(CATALOGUE[l], more[l]);
}

/** A template in one language for these parameters (a plural message: the form its number takes; its `.app` form
 * while the page speaks to a card's user, i18n/lang.ts phrasing). */
const templateOf = (code: string, params: Params, lang: Lang): string | undefined => phrased(CATALOGUE[lang], code, params, lang);

/** Every placeholder a message's forms name (a plural one's .one may leave its number out; its `.app` form may name
 * one its plain words leave out, as the server's lab2shot/messages render). */
const namesOf = (code: string, lang: Lang): Set<string> =>
  new Set([code, `${code}.one`, `${code}.other`, `${code}.app`, `${code}.app.one`, `${code}.app.other`]
    .flatMap((k) => [...(CATALOGUE[lang][k] ?? "").matchAll(PLACEHOLDER)].map((m) => m[1])));

/** A message's level: its code's first letter, as in the server's table (lab2shot/messages LEVELS, generated):
 * E error, W warning, N notice, I information, B blocked before submitting, P production risk (the one red). */
export type Level = keyof typeof LEVELS;

export const isLevel = (letter: unknown): letter is Level => typeof letter === "string" && Object.hasOwn(LEVELS, letter);

export const CODE = new RegExp(`^([${Object.keys(LEVELS).join("")}])-([A-Z][A-Z0-9]*)-([A-Z][A-Z0-9]*)$`);
const PLACEHOLDER = /\{(\w+)(?::([^{}]*))?\}/g;

/** A word of the catalogue kept by its key and parameters, said in the language its sentence is said in: a node
 * pointed at (graph/naming.ts nodeWord), and the server's words travelling the same way (lab2shot/messages wire's
 * `{"said": key, "params": {...}}`). A message kept in the log is said again in another language with it right. */
export interface Said {
  said: string;
  params?: Params;
}

type Param = string | number | boolean | null | undefined | Param[] | { text: string } | Said;
export type Params = Record<string, Param>;

const isSaid = (v: object): v is Said => typeof (v as Said).said === "string";

/** A kept word in `lang`; its key when no table of the page has it (a server word the page has no words for). */
export function sayWord(w: Said, lang: Lang = getLang()): string {
  const params = w.params ?? {};
  const template = templateFor(w.said, params, lang);
  return template === undefined ? w.said : template.replace(PLACEHOLDER, (_, name: string, spec: string | undefined) => formatValue(params[name], spec, lang));
}

export const levelOf = (code: string): Level => {
  const m = CODE.exec(code);
  if (!m) throw new Error(`not a message code: ${code}`);
  return m[1] as Level;
};

function plain(v: Param, lang: Lang): string {
  if (Array.isArray(v)) return v.map((x) => plain(x, lang)).join(listSep(lang));
  if (v && typeof v === "object") return isSaid(v) ? sayWord(v, lang) : v.text;
  return String(v ?? "");
}

/** A value with a format spec, as Python's format() writes it for the specs the catalogue allows. */
export function formatValue(v: Param, spec: string | undefined, lang: Lang = getLang()): string {
  if (spec === undefined || typeof v !== "number") return plain(v, lang);
  if (spec === "d") return String(Math.round(v));
  if (spec === ",") return v.toLocaleString("en-US", { maximumFractionDigits: 20 });
  if (spec === "g") return String(Number(v.toPrecision(6)));
  const fixed = /^\.(\d+)f$/.exec(spec);
  if (fixed) return v.toFixed(Number(fixed[1]));
  const pct = /^\.(\d+)%$/.exec(spec);
  if (pct) return `${(v * 100).toFixed(Number(pct[1]))}%`;
  throw new Error(`format ${spec} is not one of d , g .Nf .N%`);
}

/** The parameters that name a node, one of its inputs or outputs, or a line of the graph (lab2shot/messages
 * NODE_PARAMS, the same set): a message whose plain words name one, with no `.app` words of its own, is said to a card's
 * user as its level's general sentence (「<L>-APP-INSIDE」), so no node name and no wire reaches a card. */
const NODE_PARAMS = new Set(["node", "nodes", "source", "target", "input", "output", "root", "chain", "chains", "block", "inner", "outer", "ports"]);
const inside = (code: string, lang: Lang): boolean =>
  ![`${code}.app`, `${code}.app.one`, `${code}.app.other`].some((k) => k in CATALOGUE[lang])
  && [code, `${code}.one`, `${code}.other`].some((k) => [...(CATALOGUE[lang][k] ?? "").matchAll(PLACEHOLDER)].some((m) => NODE_PARAMS.has(m[1])));

/** The message's text; a parameter its template names and `params` lacks (or one it does not name) is a bug, said
 * loudly (the same check as lab2shot/messages render). */
export function render(code: string, params: Params = {}, lang: Lang = getLang()): string {
  const general = getPhrasing() === "app" && inside(code, lang) ? CATALOGUE[lang][`${levelOf(code)}-APP-INSIDE`] : undefined;
  const template = general ?? templateOf(code, params, lang);
  if (template === undefined) throw new Error(`message ${code} is not in lab2shot/i18n/<lang>/messages/web.toml`);
  const wanted = namesOf(code, lang);
  const missing = [...wanted].filter((n) => !(n in params));
  const extra = Object.keys(params).filter((n) => !wanted.has(n));
  if (missing.length || extra.length) throw new Error(`message ${code}: parameters ${missing} missing, ${extra} not in its template`);
  return template.replace(PLACEHOLDER, (_, name: string, spec: string | undefined) => formatValue(params[name], spec, lang));
}
