import { GATE_CATALOGUE, LEVELS } from "./generatedGateCatalogue";

/** Messages the page says itself, by code: the same rules as the server's lab2shot/messages (类型字母-模块-含义,
 * templates with named parameters, formats d , g .Nf .N% only, a list joined with 、). The templates are
 * lab2shot/messages/web.toml's (generated by tools/messages_web.py).
 *
 * 登录前只包含登录门所需的几条（`generatedGateCatalogue.ts`）：完整目录超过两万字节，登录门只用到其中几条。
 * 其余位于 `generatedCatalogue.ts`，登录后 site.tsx 加载时一次性注册（`addCatalogue`），登录包中不得混入完整目录。 */

/** 当前已注册的模板：初始只有登录门的一份，由 `addCatalogue` 追加。 */
const CATALOGUE: Record<string, string> = { ...GATE_CATALOGUE };

/** 追加注册一批模板（登录后的一份）。各编号在目录中不重复，因此注册顺序无关。 */
export const addCatalogue = (more: Readonly<Record<string, string>>): void => void Object.assign(CATALOGUE, more);

/** A message's level: its code's first letter, as in the server's table (lab2shot/messages LEVELS, generated):
 * E error, W warning, N notice, I information, B blocked before submitting, P production risk (the one red). */
export type Level = keyof typeof LEVELS;

export const isLevel = (letter: unknown): letter is Level => typeof letter === "string" && Object.hasOwn(LEVELS, letter);

export const CODE = new RegExp(`^([${Object.keys(LEVELS).join("")}])-([A-Z][A-Z0-9]*)-([A-Z][A-Z0-9]*)$`);
const PLACEHOLDER = /\{(\w+)(?::([^{}]*))?\}/g;

type Param = string | number | boolean | null | undefined | Param[] | { text: string };
export type Params = Record<string, Param>;

export const levelOf = (code: string): Level => {
  const m = CODE.exec(code);
  if (!m) throw new Error(`not a message code: ${code}`);
  return m[1] as Level;
};

function plain(v: Param): string {
  if (Array.isArray(v)) return v.map(plain).join("、");
  if (v && typeof v === "object") return v.text;
  return String(v ?? "");
}

/** A value with a format spec, as Python's format() writes it for the specs the catalogue allows. */
export function formatValue(v: Param, spec: string | undefined): string {
  if (spec === undefined || typeof v !== "number") return plain(v);
  if (spec === "d") return String(Math.round(v));
  if (spec === ",") return v.toLocaleString("en-US", { maximumFractionDigits: 20 });
  if (spec === "g") return String(Number(v.toPrecision(6)));
  const fixed = /^\.(\d+)f$/.exec(spec);
  if (fixed) return v.toFixed(Number(fixed[1]));
  const pct = /^\.(\d+)%$/.exec(spec);
  if (pct) return `${(v * 100).toFixed(Number(pct[1]))}%`;
  throw new Error(`format ${spec} is not one of d , g .Nf .N%`);
}

/** The message's text; a parameter its template names and `params` lacks (or one it does not name) is a bug, said
 * loudly (the same check as lab2shot/messages render). */
export function render(code: string, params: Params = {}, catalogue: Readonly<Record<string, string>> = CATALOGUE): string {
  const template = catalogue[code];
  if (template === undefined) throw new Error(`message ${code} is not in lab2shot/messages/web.toml`);
  const wanted = new Set([...template.matchAll(PLACEHOLDER)].map((m) => m[1]));
  const missing = [...wanted].filter((n) => !(n in params));
  const extra = Object.keys(params).filter((n) => !wanted.has(n));
  if (missing.length || extra.length) throw new Error(`message ${code}: parameters ${missing} missing, ${extra} not in its template`);
  return template.replace(PLACEHOLDER, (_, name: string, spec: string | undefined) => formatValue(params[name], spec));
}
