// Generated by tools/messages_web.py from lab2shot/messages/web.toml: do not edit (edit the .toml, run the tool).
// 登录门（main.tsx 静态能到的那几个文件）真用到的消息，加上级别表：登录前只发这一份。
export const GATE_CATALOGUE: Readonly<Record<string, string>> = {
  "E-GATE-NOANSWER": "服务器没有回答（HTTP {status}），稍后刷新再试",
  "E-GATE-UNREACHABLE": "连不上服务器：稍后刷新再试；一直连不上就找管理员看服务是否正在运行",
  "E-REQUEST-REFUSED": "服务器拒绝了请求（HTTP {status}）：{detail}",
  "E-PAGE-ERROR": "页面出错：{detail}。这是网页的问题，打开「日志」复制给技术人员",
  "I-PAGE-LOADING": "正在读取{what}…",
};

// The message levels, the server's own table (lab2shot/messages LEVELS): a code's first letter and what it is.
export const LEVELS = {
  E: "error",
  W: "warning",
  N: "notice",
  I: "info",
  B: "blocked",
  P: "production-risk",
} as const;
