import { GATE_WORDS } from "../messages/generatedGateCatalogue.ts";
import { getLang, getPhrasing, LANGS, type Lang } from "./lang.ts";

/** The page's own words by key, one table per language (lab2shot/i18n/<lang>/ui/*.toml, generated by
 * tools/messages_web.py): before login only the gate's few (generatedGateCatalogue.ts), the rest registered by site.tsx
 * once it loads (`addWords`). Every key is in both languages (lab2shot check i18n): none is read in the other.
 *
 * A sentence that follows a number is written in plural forms, `<key>.one` / `<key>.other` (English both, Chinese only
 * other; lab2shot/i18n PLURAL_FORMS): `templateFor` picks the one its number takes. */

const WORDS: Record<Lang, Record<string, string>> = Object.fromEntries(LANGS.map((l) => [l, { ...GATE_WORDS[l] }])) as Record<Lang, Record<string, string>>;

/** Registers more words (the post-login set). */
export function addWords(more: Readonly<Record<Lang, Readonly<Record<string, string>>>>): void {
  for (const l of LANGS) Object.assign(WORDS[l], more[l]);
}

/** A word's template in `lang` (default: the page's) as written; undefined: none. */
export function lookup(key: string, lang: Lang = getLang()): string | undefined {
  return WORDS[lang][key];
}

const PLACEHOLDER = /\{(\w+)(?::[^{}]*)?\}/g;

/** Which plural form a number takes (lab2shot/i18n plural_form): English one for exactly 1, else other; Chinese
 * always other. */
export const pluralForm = (lang: Lang, n: unknown): "one" | "other" => (lang === "en" && asNumber(n) === 1 ? "one" : "other");

/** A parameter as a number, when it is one: a number, or one already written out ("1", "1,234"). */
export function asNumber(v: unknown): number | undefined {
  if (typeof v === "number") return v;
  if (typeof v === "string" && /^-?\d[\d,]*(\.\d+)?$/.test(v.trim())) return Number(v.trim().replace(/,/g, ""));
  return undefined;
}

/** The number a plural sentence follows (lab2shot/i18n plural_count): the parameter `count`, else the first
 * placeholder of its `.other` template given a number (a number written out as text counts too). */
export function pluralCount(template: string, params: Readonly<Record<string, unknown>>): number | undefined {
  if ("count" in params) return asNumber(params.count);
  for (const m of template.matchAll(PLACEHOLDER)) {
    const n = asNumber(params[m[1]]);
    if (n !== undefined) return n;
  }
  return undefined;
}

/** The template of a key with these parameters out of one table: its own, else the plural form its number takes. */
export function pluralOf(table: Readonly<Record<string, string>>, key: string, params: Readonly<Record<string, unknown>>, lang: Lang): string | undefined {
  const own = table[key];
  if (own !== undefined) return own;
  const other = table[`${key}.other`];
  if (other === undefined) return undefined;
  return pluralForm(lang, pluralCount(other, params)) === "one" ? table[`${key}.one`] ?? other : other;
}

/** The `.app` form of a key (its words for whoever uses a card, lab2shot/i18n APP_SUFFIX), else the key's own: out of
 * one table, with the plural form its number takes. Only while the page speaks to a card's user (i18n/lang.ts phrasing). */
export function phrased(table: Readonly<Record<string, string>>, key: string, params: Readonly<Record<string, unknown>>, lang: Lang): string | undefined {
  return (getPhrasing() === "app" ? pluralOf(table, `${key}.app`, params, lang) : undefined) ?? pluralOf(table, key, params, lang);
}

/** A word's template in `lang` for these parameters (a plural sentence: the form its number takes; its `.app` form
 * while the page speaks to a card's user). */
export const templateFor = (key: string, params: Readonly<Record<string, unknown>>, lang: Lang = getLang()): string | undefined =>
  phrased(WORDS[lang], key, params, lang);

/** How a list is joined in a sentence (、 in Chinese, ", " in English). */
export const listSep = (lang: Lang = getLang()): string => lookup("list.sep", lang) ?? ", "; // list.sep is always in the gate's words
