"""Generate the DCC panel's look from the page's own design values (设计_DCC新面板.md §2): one source, never a copy.

1. webui/src/ui/tokens.css: every `--x: value;` of its `:root` blocks, `var(--y)` put in, the solid fallback of the
   `@supports not (backdrop-filter …)` block over the glass values (Qt has no background blur: the page's own fallback,
   no value of our own); colours in rgba() made Qt's rgba(r, g, b, 0–255).
2. lab2shot/data/types.py COLOURS: the data types' colours (the page's wire colours), for a card's 「需要：」 dots.
3. Writes clients/common/lab2shot_dcc/ui/tokens.json ({"tokens": {name without --: value}, "types": {type: colour}})
   and fills clients/common/lab2shot_dcc/ui/theme.qss.in (Qt rules only, every value an @{token}) into theme.qss.
   A type size becomes whole pixels (Qt's pixel sizes are whole).

    uv run python tools/dcc_theme.py          # write both
    uv run python tools/dcc_theme.py --check  # exit with status 1 when either is out of date
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

TOKENS_CSS = ROOT / "webui" / "src" / "ui" / "tokens.css"
UI = ROOT / "clients" / "common" / "lab2shot_dcc" / "ui"
TEMPLATE, QSS, JSON_OUT = UI / "theme.qss.in", UI / "theme.qss", UI / "tokens.json"

_DECL = re.compile(r"--([A-Za-z0-9-]+)\s*:\s*([^;]+);")
_VAR = re.compile(r"var\(--([A-Za-z0-9-]+)\)")
_RGBA = re.compile(r"rgba\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*\)")
_PLACE = re.compile(r"@\{([A-Za-z0-9-]+)\}")
_PX = re.compile(r"^(\d+(?:\.\d+)?)px$")


def _blocks(css: str) -> tuple[str, str]:
    """(every top-level :root block, the @supports-not fallback's :root block)."""
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    plain, fallback, depth, start, kind = [], [], 0, 0, ""
    i = 0
    while i < len(css):
        ch = css[i]
        if ch == "{":
            if depth == 0:
                head = css[start:i].split(";")[-1].strip()
                kind = "root" if head == ":root" else ("fallback" if head.startswith("@supports not") else "other")
            depth += 1
            if depth == 1:
                body_start = i + 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                body = css[body_start:i]
                (plain if kind == "root" else fallback if kind == "fallback" else []).append(body)
                start = i + 1
        i += 1
    return "\n".join(plain), "\n".join(fallback)


def tokens() -> dict[str, str]:
    plain, fallback = _blocks(TOKENS_CSS.read_text(encoding="utf-8"))
    values = {k: " ".join(v.split()) for k, v in _DECL.findall(plain)}
    values.update({k: " ".join(v.split()) for k, v in _DECL.findall(fallback)})

    def resolve(v: str, seen: tuple = ()) -> str:
        return _VAR.sub(lambda m: resolve(values[m.group(1)], (*seen, m.group(1))) if m.group(1) not in seen else "", v)

    out = {}
    for k, v in values.items():
        v = resolve(v)
        v = _RGBA.sub(lambda m: f"rgba({m.group(1)}, {m.group(2)}, {m.group(3)}, {round(float(m.group(4)) * 255)})", v)
        if k.startswith("fs-") and (m := _PX.match(v)):
            v = f"{round(float(m.group(1)))}px"
        out[k] = v
    return out


def data_type_colours() -> dict[str, str]:
    from lab2shot.data.types import COLOURS, UNKNOWN_COLOUR

    return {**dict(COLOURS), "": UNKNOWN_COLOUR}


def written() -> tuple[str, str]:
    t = tokens()
    missing = sorted({m for m in _PLACE.findall(TEMPLATE.read_text(encoding="utf-8")) if m not in t})
    if missing:
        raise SystemExit(f"theme.qss.in names tokens tokens.css does not have: {', '.join(missing)}")
    qss = "/* generated by tools/dcc_theme.py from theme.qss.in and webui/src/ui/tokens.css; do not edit */\n" + \
        _PLACE.sub(lambda m: t[m.group(1)], TEMPLATE.read_text(encoding="utf-8"))
    data = json.dumps({"tokens": t, "types": data_type_colours()}, ensure_ascii=False, indent=1, sort_keys=True) + "\n"
    return qss, data


def main() -> int:
    qss, data = written()
    if "--check" in sys.argv:
        same = QSS.is_file() and JSON_OUT.is_file() and QSS.read_text(encoding="utf-8") == qss \
            and JSON_OUT.read_text(encoding="utf-8") == data
        print("up to date" if same else "theme.qss / tokens.json are not up to date: run uv run python tools/dcc_theme.py")
        return 0 if same else 1
    QSS.write_text(qss, encoding="utf-8")
    JSON_OUT.write_text(data, encoding="utf-8")
    print(f"wrote {QSS.relative_to(ROOT)} and {JSON_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
