"""Generate the DCC client's words into the generated block of lab2shot/client.py (between the BEGIN and END lines):
for each language (lab2shot/i18n LANGS), the client's messages (i18n/<lang>/messages/client.toml), the DCC plugins'
own words (i18n/<lang>/dcc.toml, keys dcc.*), the languages' names (lang.*), the list separator (list.*), the data
types' names (type.<id>.label, type.or, type.list_of: i18n/<lang>/types.toml) and the conditions' words (ui.conditions.*, said by engine/conditions.py in a plugin). The client remains a single
standard-library file and defines no text of its own; both languages have the same keys (lab2shot check i18n), a
sentence that follows a number in its plural forms (<key>.one / <key>.other: client.text picks).

    uv run python tools/messages_client.py          # write the block
    uv run python tools/messages_client.py --check  # exit with status 1 if the block is out of date
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

TARGET = ROOT / "lab2shot" / "client.py"
BEGIN = "# ---- messages: generated by tools/messages_client.py from lab2shot/i18n/<lang>/messages/client.toml and dcc.toml; do not edit\n"
END = "# ---- end of the generated messages\n"
WORDS = ("dcc.", "lang.", "list.", "ui.conditions.")  # ui.conditions.*: the conditions' words (engine/conditions.py say), shared with the page
TYPE_WORDS = ("type.or", "type.list_of")  # with every type.<id>.label: the data types' names (a tool card's 「需要：画面、摄影机」)


def _wanted(key: str) -> bool:
    return key.startswith(WORDS) or key in TYPE_WORDS or (key.startswith("type.") and key.endswith(".label"))


def table(lang: str) -> dict[str, str]:
    from lab2shot import i18n
    from lab2shot.messages import _read

    out = dict(_read(i18n.lang_dir(lang) / "messages" / "client.toml"))
    words: dict[str, str] = {}
    for path in i18n.word_files(lang):  # the core's word files only: no extension's words reach the client
        words.update(i18n.read(path))
    out.update({k: v for k, v in sorted(words.items()) if _wanted(k)})
    return out


def block() -> str:
    from lab2shot import i18n

    parts = [BEGIN, "_MESSAGES = {\n"]
    for lang in i18n.LANGS:
        parts.append(f"    {json.dumps(lang)}: {{\n")
        parts += [f"        {json.dumps(code)}: {json.dumps(text, ensure_ascii=False)},\n" for code, text in table(lang).items()]
        parts.append("    },\n")
    parts += ["}\n", END]
    return "".join(parts)


def written(text: str) -> str:
    """Return `text` (the client source) with the generated block regenerated from the catalogue."""
    start = text.index("# ---- messages: generated by tools/messages_client.py")
    end = text.index(END) + len(END)
    return text[:start] + block() + text[end:]


def main() -> int:
    text = TARGET.read_text(encoding="utf-8")
    new = written(text)
    if "--check" in sys.argv:
        print("up to date" if new == text else f"{TARGET.relative_to(ROOT)} is not up to date: run uv run python tools/messages_client.py")
        return 0 if new == text else 1
    TARGET.write_text(new, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
