"""生成网页端的消息表，分为两个文件（lab2shot/messages/web.toml -> webui/src/messages/）。

网页自身产生的消息（提交前的拦截、页面自身操作遇到的问题）与服务器一样按编号引用；消息文本统一维护在消息目录中，
本工具据此生成上述文件，生成文件不得手工编辑。tests/test_messages.py 校验二者一致。

完整目录超过 20 KB，而登录门仅使用其中十余条，登录前无需全部下发。因此按登录门静态可达的文件拆分为两份：

  - `generatedGateCatalogue.ts`  登录门实际使用的编号，以及级别表（format.ts 始终依赖该表）；
  - `generatedCatalogue.ts`      其余消息，登录后由 site.tsx 一次性注册（messages/format.ts addCatalogue）。

登录门可达的文件由 `main.tsx` 出发沿静态 import 遍历得出，规则与 webui/tests/bundle.test.ts 相同：
计入 `import ... from`、`export ... from`、`import "x.css"`；`import()` 为按需加载，不计入。登录门新增使用的消息
会使 `--check` 报告两个文件已过期；相应的约束由 webui/tests/bundle.test.ts 执行。

    uv run python tools/messages_web.py          # 写入两个文件
    uv run python tools/messages_web.py --check  # 文件未更新时以状态码 1 退出
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from lab2shot_shared.protocol import CODE, CODE_CANDIDATE  # noqa: E402  (the one rule; the finder is looser, see there)

SOURCE = ROOT / "lab2shot" / "messages" / "web.toml"
WEB_SRC = ROOT / "webui" / "src"
TARGET = WEB_SRC / "messages" / "generatedCatalogue.ts"
GATE_TARGET = WEB_SRC / "messages" / "generatedGateCatalogue.ts"
GATE_ENTRY = "main.tsx"  # 登录前浏览器加载的入口（webui/index.html）

STATIC = re.compile(r"(?:^|\n)\s*(?:import|export)\s+(?:type\s+)?(?:[\s\S]*?\sfrom\s+)?[\"']([^\"']+)[\"']")


# 页面在提交前自行给出的服务器拒绝消息（编号、文本与模板均与服务器相同）。这些消息归服务器目录所有，
# web.toml 不重复定义，在生成时从服务器目录复制。页面代码（webui/src）使用而页面目录缺失的编号会导致
# `msg()` 在运行时抛出异常（format.ts），因此页面开始自行使用某个服务器编号时，必须将其加入此元组。
# 例如 `B-WIRE-OUTINACTIVE`（engine.toml）：webui/src/graph/edit.ts 在向未激活的输出端口提交连线前使用该消息。
FROM_SERVER: tuple[str, ...] = ("B-WIRE-OUTINACTIVE",)


def _resolve(from_file: Path, spec: str) -> Path | None:
    if not spec.startswith("."):
        return None  # 包导入
    p = (from_file.parent / spec).resolve()
    for c in (p, p.with_suffix(p.suffix + ".ts"), p.with_suffix(p.suffix + ".tsx"), p / "index.ts", p / "index.tsx"):
        if c.is_file() and c.suffix in (".ts", ".tsx"):  # 仅跟踪代码文件；样式与图片中不含消息编号
            return c
    return None


def gate_files() -> list[Path]:
    """返回登录前静态加载的全部文件（自 main.tsx 起沿 import 遍历）。"""
    seen: set[Path] = set()
    todo = [WEB_SRC / GATE_ENTRY]
    while todo:
        f = todo.pop()
        if f in seen or not f.is_file():
            continue
        seen.add(f)
        text = f.read_text(encoding="utf-8")
        for m in STATIC.finditer(re.sub(r"/\*[\s\S]*?\*/|//.*$", "", text, flags=re.M)):
            if m.group(0).strip().startswith("import type"):
                continue
            if (r := _resolve(f, m.group(1))) is not None:
                todo.append(r)
    return sorted(seen)


def gate_codes() -> set[str]:
    """返回登录门相关文件中出现的消息编号（不含两个生成文件本身）。"""
    out: set[str] = set()
    for f in gate_files():
        if f.name in (TARGET.name, GATE_TARGET.name):
            continue
        out |= {c for c in CODE_CANDIDATE.findall(f.read_text(encoding="utf-8")) if CODE.match(c)}
    return out


def templates() -> dict[str, str]:
    from lab2shot.messages import CORE_DIR, _read

    said = _read(SOURCE)
    server = {code: text for path in sorted(CORE_DIR.glob("*.toml")) if path != SOURCE for code, text in _read(path).items()}
    missing = [code for code in FROM_SERVER if code not in server]
    if missing:
        raise SystemExit(f"FROM_SERVER names codes the server's catalogue does not have: {missing}")
    return {**said, **{code: server[code] for code in FROM_SERVER}}


def _entries(items: dict[str, str]) -> list[str]:
    return [f"  {json.dumps(code)}: {json.dumps(text, ensure_ascii=False)}," for code, text in items.items()]


def generated() -> tuple[str, str]:
    """返回（登录门文件, 其余消息文件）的内容。"""
    from lab2shot.messages import LEVELS

    all_templates = templates()
    wanted = gate_codes()
    gate = {code: text for code, text in all_templates.items() if code in wanted}
    rest = {code: text for code, text in all_templates.items() if code not in wanted}
    head = "// Generated by tools/messages_web.py from lab2shot/messages/web.toml: do not edit (edit the .toml, run the tool)."
    gate_text = "\n".join([
        head,
        "// 登录门（main.tsx 静态能到的那几个文件）真用到的消息，加上级别表：登录前只发这一份。",
        "export const GATE_CATALOGUE: Readonly<Record<string, string>> = {",
        *_entries(gate),
        "};",
        "",
        "// The message levels, the server's own table (lab2shot/messages LEVELS): a code's first letter and what it is.",
        "export const LEVELS = {",
        *(f"  {letter}: {json.dumps(name)}," for letter, name in LEVELS.items()),
        "} as const;",
        "",
    ])
    rest_text = "\n".join([
        head,
        "// The page's own messages by code; a message from the server comes with its text.",
        "// 登录之后才发的那一份：site.tsx 加载时注册进 messages/format.ts（登录门那几条在 generatedGateCatalogue.ts）。",
        "export const CATALOGUE: Readonly<Record<string, string>> = {",
        *_entries(rest),
        "};",
        "",
    ])
    return gate_text, rest_text


def main() -> int:
    gate_text, rest_text = generated()
    wrote = ((GATE_TARGET, gate_text), (TARGET, rest_text))
    if "--check" in sys.argv:
        stale = [p for p, text in wrote if not p.is_file() or p.read_text(encoding="utf-8") != text]
        print("up to date" if not stale else
              "not up to date, run uv run python tools/messages_web.py: " + "、".join(p.relative_to(ROOT).as_posix() for p in stale))
        return 0 if not stale else 1
    for path, text in wrote:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
