"""Generate the DCC client's message table from lab2shot/messages/client.toml into the generated block of
lab2shot/client.py (between the BEGIN and END lines). The client remains a single standard-library file and defines no
message text of its own; all text comes from the catalogue. tests/test_messages.py verifies that the block is current.

    uv run python tools/messages_client.py          # write the block
    uv run python tools/messages_client.py --check  # exit with status 1 if the block is out of date
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

SOURCE = ROOT / "lab2shot" / "messages" / "client.toml"
TARGET = ROOT / "lab2shot" / "client.py"
BEGIN = "# ---- messages: generated by tools/messages_client.py from lab2shot/messages/client.toml; do not edit\n"
END = "# ---- end of the generated messages\n"


def block() -> str:
    from lab2shot.messages import _read

    rows = "".join(f"    {json.dumps(code)}: {json.dumps(text, ensure_ascii=False)},\n" for code, text in _read(SOURCE).items())
    return BEGIN + "_MESSAGES = {\n" + rows + "}\n" + END


def written(text: str) -> str:
    """Return `text` (the client source) with the generated block regenerated from the catalogue."""
    start, end = text.index(BEGIN), text.index(END) + len(END)
    return text[:start] + block() + text[end:]


def main() -> int:
    text = TARGET.read_text(encoding="utf-8")
    new = written(text)
    if "--check" in sys.argv:
        print("up to date" if new == text else f"{TARGET.relative_to(ROOT)} is not up to date: run uv run python tools/messages_client.py")
        return 0 if new == text else 1
    TARGET.write_text(new, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
