"""EnvSpec.build for Mesh4D, run with the environment's own Python.

Three steps that upstream's setup performs inside its checkout and this script performs beside it:

1. the tree its scripts expect, composed out of symlinks (codebase.py);
2. `hy3dshape/setup_im2mesh.py build_ext --inplace`: five Cython modules. One of them,
   pykdtree, ships a `kdtree.c` generated by an old Cython that still writes `tp_print`,
   which does not compile on Python 3.9+; upstream's `kdtree.pyx` is included, so it is
   transpiled again with this environment's Cython and the generated C is compiled;
3. the denoiser, written out once as fp16 safetensors. The authors publish a 24 GB Lightning
   training archive (weights + optimizer state); upstream's infer.py `torch.load`s the whole
   archive on every run, taking about a minute and tens of GB of RAM each time. The same tensors
   `infer.py` would hand to `load_state_dict` are saved here instead (same key rewrite, and the
   image-encoder keys `load_state_dict(strict=False)` drops are left out), so a cook loads
   ~4 GB in seconds. The computation is unchanged: infer.py converts the model to half
   precision right after loading.

The texture pass (hy3dpaint: custom_rasterizer's CUDA rasteriser and DifferentiableRenderer's
C++ inpainter, plus 7 GB of Hunyuan3D paint weights) is not built: this node delivers the
mesh sequence only.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from lab2shot_worker.build import run

sys.path.insert(0, str(Path(__file__).resolve().parent))
from codebase import compose  # noqa: E402  (the adapter's own module, next to this script)

ext_root = Path(os.environ["LAB2SHOT_EXT_ROOT"])

print("Composing the Mesh4D code folder (symbolic links, the repository is left as it is)", flush=True)
lay = compose(ext_root)

# ------------------------------------------------------------------ the five Cython modules
shape = lay.shape
pyx = shape / "im2mesh" / "utils" / "libkdtree" / "pykdtree" / "kdtree.pyx"
print("Regenerating pykdtree's C (the copy in the repository was made by an old Cython and does not compile on Python 3.10)", flush=True)
run([Path(sys.executable).parent / "cython", "-3", pyx.name], cwd=pyx.parent)
print("Compiling the 5 Cython modules of im2mesh", flush=True)
run([sys.executable, "setup_im2mesh.py", "build_ext", "--inplace"], cwd=shape)

# ------------------------------------------------------------------ the denoiser, once
import torch  # noqa: E402  (only needed here, and torch is installed before the build step)
from safetensors.torch import save_file  # noqa: E402

out = lay.weights / "denoiser.fp16.safetensors"
if not out.exists():
    src = lay.weights / "ckpt" / "denoiser.ckpt"
    print(f"Reducing the 24 GB training archive to inference weights: {out.name} (once; every cook then reads only this)", flush=True)
    # identical to the line in infer.py: strip "model." from every state_dict key
    state = torch.load(src, map_location="cpu")["state_dict"]
    state = {k.replace("model.", ""): v for k, v in state.items()}
    # keys that load_state_dict(strict=False) drops (the image encoder is loaded from DINOv2): not stored
    keep = {k: v.to(torch.float16).contiguous() for k, v in state.items()
            if not k.startswith("cond_stage_main_image_encoder.")}
    del state
    tmp = out.with_suffix(".part")
    save_file(keep, str(tmp))
    tmp.replace(out)
    print(f"Wrote {len(keep)} tensors, {out.stat().st_size / 1e9:.1f} GB", flush=True)

print("Mesh4D environment ready", flush=True)
